### ISSUE TITLE
Problems resolving a NameExpr when it represents a private field name

### ISSUE THREAD

**Issue by hecaidi** [javaparser/javaparser#2367] opened 2019-09-17 11:47 UTC
Hello,

I am having problems with 
`((NameExpr) node).resolve().getType().describe()`
when the node represents the name of a private field.

An exception is thrown at the `resolve()` call. I think the problem comes from class **com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext**, at the method:
```
@Override
    public SymbolReference<? extends ResolvedValueDeclaration> solveSymbol(String name) {
        if (typeSolver == null) throw new IllegalArgumentException();

        if (this.getDeclaration().hasVisibleField(name)) {
            return SymbolReference.solved(this.getDeclaration().getVisibleField(name));
        }

        // then to parent
        return getParent().solveSymbol(name);
    }
```
I don't understand why it is only searching for visible fields, being the **ClassOrInterfaceDeclaration** a parent of my **NameExpr** node.

Should I do this in other way?

**Comment by SimonBaars** [comment] 2019-09-18 18:21
Hey Hecaidi,

Thanks for submitting this issue! Could you please submit a reproducible case in which this error occurs? `hasVisibleField` is correct in the method you point out because the symbol solver traces to parent classes and this method should only be in effect in such cases.

I created the following class:
```
public class Issue2367 {

    private double privateField;

    public Issue2367(double localField) {
        privateField = localField;
    }
}
```

Resolving the `privateField` `NameExpr` in `privateField = localField;` succeeds.

**Comment by SimonBaars** [comment] 2019-09-18 18:54
Okay, hereby some further insight into solving this issue.

The method you pointed out breaks a test when `hasVisibleField` and `getVisibleField` are changed to `hasField` and `getField` respectively. However, the following (similar) method in the same file does not break tests when the same transformation is applied:
```
@Override
    public Optional<Value> solveSymbolAsValue(String name) {
        if (typeSolver == null) throw new IllegalArgumentException();

        if (this.getDeclaration().hasVisibleField(name)) {
            return Optional.of(Value.from(this.getDeclaration().getVisibleField(name)));
        }

        // then to parent
        return getParent().solveSymbolAsValue(name);
    }
```
Inspecting the incoming calls of both, it seems that `solveSymbol` is used when parsing through inheritance hierarchies but `solveSymbolAsValue` is not. 

I solved the problem in my fork here:
https://github.com/SimonBaars/javaparser/tree/issue2367

If I can test this fix successfully using a case you can provide, I can open a pull request to close this issue.

**Closed as completed** 2019-09-24 10:14 UTC
Labels: Question (JP usage), Symbol Solver
