### ISSUE TITLE
Q: How to convert ResolvedType to Type, To creating VariableDeclarator

### ISSUE THREAD

**Issue by seoj135** [javaparser/javaparser#1536] opened 2018-05-08 08:19 UTC
I fellow up issues. But no information was found for this question.

I used `JavaParser.parseClassOrInterfaceType(String)`. I think this method isn't valid to use.

I use for this example
```
enum ENUM { AA, BB, CC };
// target source code
private void proc(ENUM e) {
   switch(e) {
   case AA: break;
   case BB: break;
   case CC: break;
   }
}
```
```
// JSS
SwitchStmt stmt = getSwitch();  // some method to get target SwitchStmt
ResolvedType rt = JavaParserFacade.get(^typesolver).getType(stmt.getSelector()); or stmt.getSelector().calculateResolvedType();

VariableDeclarator vd = new VariableDeclarator(^type instance, " name ", ^expr);
```

**Comment by matozoid** [comment] 2018-09-20 16:54
@ftomassetti - looks like we missed this question, oops!

**Comment by ftomassetti** [comment] 2018-09-20 17:42
Do we need a policy about answer? Like closing them if they are not unaswered within 2 weeks?

**Comment by matozoid** [comment] 2018-09-20 17:55
Well, I think it's nice to at least ask @seoj135 if the question is still relevant.

**Comment by seoj135** [comment] 2018-09-20 18:29
@ftomassetti @matozoid 
Oh! Thank you to concern about it. I done project using javaparser. So I don't need it now.

But if method that convert ResolvedType to Type is supported, It'll be great.

Thank you.

**Comment by matozoid** [comment] 2020-02-26 09:28
I think that method has been added now.

**Closed as completed by matozoid** 2020-02-26 09:28 UTC
Labels: Question (JP usage), Symbol Solver

**Comment by pcantrell** [comment] 2021-09-12 03:15
I came to this issue with the exact same question. If the method has been added, as @matozoid says, I’m afraid I can’t find it: no public methods of `ResolvedType` return `Type`. Am I just missing something obvious?

**Comment by matozoid** [comment] 2021-09-12 10:33
If I'm not mistaken, it is available only on the types resolved to source files, so some casting has to be done first. Too long ago to remember :-(
If your wish is simply to create a Type node, just instantiate one of its subclasses - https://javadoc.io/doc/com.github.javaparser/javaparser-core/latest/com/github/javaparser/ast/type/Type.html - and if you think that's useful functionality, leave a PR here :-)

**Comment by jlerbsc** [comment] 2021-09-12 13:11
Hi @pcantrell can you specify what you want to do maybe there are other ways to achieve it. An example would be welcome.

**Comment by pcantrell** [comment] 2021-09-12 14:11
I want to do expression rearrangements that involve introducing variable declarations. For example, I’d like to be able to extract a subexpression to its own local variable, e.g. `double a = b + (c * d);` → `int tmp = c * d; double a = b + tmp;`.

The problem is that declaring `tmp` here requires translating the resolved type of the subexpression into a variable declaration type, but `calculateResolvedType()` returns `ResolvedType` and the `VariableDeclarator` constructors all expect a `Type`. AFAICT, there’s no tidy way to do this.

---

It does seem that I can cheat by making a “class” whose name is actually the full (maybe package-qualified, maybe generic, maybe primitive) name of the resolved type: `new ClassOrInterfaceType(null, subexpr.calculateResolvedType().describe())`. That, however, seems like asking for trouble in the future.

Similarly, if I’m emitting more recent Java versions, it’s possible to make a class named `var` — but again, cheating like that seems like asking for trouble (and fails when introducing a method param instead of a local var).

---

Ideally, I’d like to be able to call an `asType()` method on `ResolvedType` that returns `Type`, like this:

```java
new VariableDeclarator(
    subexpr.calculateResolvedType().asType(),
    varName)
```

If that makes sense to you, I could submit a PR. And if there’s a way to do all this that I’m missing, let me know!

**Comment by matozoid** [comment] 2021-09-12 15:09
Calling @MysterAitch and @jlerbsc :-)

**Comment by pkesseli** [comment] 2021-10-13 21:22
Any update or recommendation on this issue? We are facing the same problem in our project.

**Comment by jlerbsc** [comment] 2021-10-14 09:57
To my knowledge there is no ready-made builder to return a Type from a ResolvedType but you can certainly create a utility class that performs this function.

**Comment by seoj135** [comment] 2021-10-14 10:08
Hello guys, I surprised since it notify me :), I leave a way how I did solve this issue for my project. I hope it helps you.

```
/* type utils */
Type getRefType(ResolvedType resolved) {
	if(resolved.isPrimitive()) {
		ResolvedPrimitiveType asPrimitive = resolved.asPrimitive();
		switch(asPrimitive.describe().toLowerCase()) {
		case "byte": return new PrimitiveType(Primitive.BYTE);
		case "short": return new PrimitiveType(Primitive.SHORT);
		case "char": return new PrimitiveType(Primitive.CHAR);
		case "int": return new PrimitiveType(Primitive.INT);
		case "long": return new PrimitiveType(Primitive.LONG);
		case "boolean": return new PrimitiveType(Primitive.BOOLEAN);
		case "float": return new PrimitiveType(Primitive.FLOAT);
		case "double": return new PrimitiveType(Primitive.DOUBLE);
		}
	} 
//	else if(resolved.isArray()) {
//		ResolvedArrayType asArrayType = resolved.asArrayType();
//	}
	return JavaParser.parseClassOrInterfaceType(resolved.describe());
}
```
