### ISSUE TITLE
Illegal line feed of comments

### ISSUE THREAD

**Issue by YinWangPing** [javaparser/javaparser#2771] opened 2020-08-03 07:48 UTC
Test Case：
```java
    public static int calculate(int []nums){
        if(nums.length<10){
            return nums.length/10
                    +1000000;// return the result
        }else {
            return nums.length;
        }
    }
```

Result:
```java
    public static int calculate(int[] nums) {
        if (nums.length < 10) {
            /* We should pass arguments in here */
            return nums.length / 10 + // return the result
            1000000;
        } else {
            return nums.length;
        }
    }
```

**Comment by jlerbsc** [comment] 2020-10-04 17:22
@YinWangPing Could you give us more inputs please?

**Comment by jlerbsc** [comment] 2020-11-18 17:57
We can reproduce this issue with the pretty printer

    public void test() {
        String code = 
                "public class A {\n" +
                "  public static int calculate(int []nums){\n" + 
                "        if(nums.length<10){\n" + 
                "            return nums.length/10\n" + 
                "                    +1000000;// return the result\n" + 
                "        }else {\n" + 
                "            return nums.length;\n" + 
                "        }\n" + 
                "    }\n" +
                "}\n";

        CompilationUnit cu = StaticJavaParser.parse(code);
        System.out.println(cu.toString());
    }

**Comment by jlerbsc** [comment] 2020-11-18 18:11
This issue is raised because the comment is associated to the right hand of the binary expression (the IntegerLiteralExpr represented by "1000000"). Pretty printer which is used by default when you call cu.toString() prints IntegerLiteralExpr with the following steps : 1- print orphan comment 2- print comment on the node 3- print the value of the node

If you want to keep the original format you have to use the LexicalPreservingPrinter.

    String code = 
                "public class A {\n" +
                "  public static int calculate(int []nums){\n" + 
                "        if(nums.length<10){\n" + 
                "            return nums.length/10\n" + 
                "                    +1000000;// return the result\n" + 
                "        }else {\n" + 
                "            return nums.length;\n" + 
                "        }\n" + 
                "    }\n" +
                "}\n";

        CompilationUnit cu = StaticJavaParser.parse(code);
        LexicalPreservingPrinter.setup(cu);
        System.out.println(LexicalPreservingPrinter.print(cu));

**Comment by MysterAitch** [comment] 2020-11-18 23:11
Personally I am still unsure what the question is, but I agree with @jlerbsc that it hasn't been possible to see any problems with JavaParser itself (perhaps the problem is setting up the lexical preserving printer as noted above?). 

Given this I'll close this issue, but @YinWangPing please do comment if there's something we've missed and we can reopen it and help you! :+1: 

---

Sidenote: Here is the slightly modified test case I used -- note that the end of line comment can be moved around to different locations and it seems to work okay (at least, I wasn't able to make it fail).

```java 
    @Test
    public void test() {
        String input = "" +
                "public class A {\n" +
                "      public static int calculate(int[] nums) {\n" +
                "        if (nums.length < 10) {\n" +
                "            /* We should pass arguments in here */\n" +
                "            return nums.length / 10 + // return the result\n" +
                "            1000000;\n" +
                "        } else {\n" +
                "            return nums.length;\n" +
                "        }\n" +
                "    }\n" +
                "}\n";

        CompilationUnit cu = StaticJavaParser.parse(input);
        LexicalPreservingPrinter.setup(cu); // alternatively, pass in a configuration with LexicalPreservationEnabled e.g. `new ParserConfiguration().setLexicalPreservationEnabled(true)`

        String output = LexicalPreservingPrinter.print(cu);
        System.out.println(output);

        assertEquals(input, output, "the input code and the LexicalPreservingPrinter output must match");
    }
```

**Closed as completed by MysterAitch** 2020-11-18 23:11 UTC
Labels: Need more input, Printers
