### ISSUE TITLE
confused on MethodDeclaration

### ISSUE THREAD

**Issue by MornSunShine** [javaparser/javaparser#2737] opened 2020-06-28 03:04 UTC
Nested function calls may not been resolved.
new Query.Builder().setSortOrder(sortOrder).build() can be solved ,
however,
like new Query.Builder().addFilter(Filters.eq(SearchableField.TITLE, "glucosio.realm")) , arguments of the method are MethodCallExpr nodes, JavaParserFacade will  throw exception,
java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call.

Are there ways to deal with it?

**Comment by jlerbsc** [comment] 2020-10-06 17:51
Hi @MornSunShine Please could update this test case to reproduce your issue?

    public void test() {
        String actual = 
                "public class Query {\n" + 
                "    public static class Order {\n" + 
                "        String order;\n" + 
                "\n" + 
                "        public Order(String o) {\n" + 
                "            this.order = o;\n" + 
                "        }\n" + 
                "\n" + 
                "        public String toString() {\n" + 
                "            return order;\n" + 
                "        }\n" + 
                "    }\n" + 
                "\n" + 
                "    public static void main(String[] args) {\n" + 
                "            Order order = new Order(\"asc\");\n" + 
                "            Query.builder().setSortOrder(order.toString());\n" + 
                "        }\n" + 
                "\r\n" + 
                "    public static Query builder() {\n" + 
                "        return new Query();\n" + 
                "    }\n" + 
                "\n" + 
                "    public Query setSortOrder(String order) {\n" + 
                "        return this;\n" + 
                "    }\n" + 
                "}";
        CombinedTypeSolver typeSolver = new CombinedTypeSolver();
        typeSolver.add(new ReflectionTypeSolver(false));

        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(typeSolver);
        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

        CompilationUnit cu = StaticJavaParser.parse(actual);
        MethodCallExpr mce = cu.findFirst(MethodCallExpr.class).get();
        System.out.println(mce.resolve().toString());
        mce.getArguments().forEach(a-> System.out.println(a.calculateResolvedType().toString()));
    }

**Comment by jlerbsc** [comment] 2024-02-07 09:39
I'm closing this door because we can't try to solve a problem that we don't know how to test.
If you can provide a simple test case then you can reopen this issue.

**Closed as completed by jlerbsc** 2024-02-07 09:39 UTC
