### ISSUE TITLE
Lexical preserving printer introduces or removes line breaks

### ISSUE THREAD

**Issue by Sebsen** [javaparser/javaparser#1293] opened 2017-12-15 09:02 UTC
Hello guys! Playing around with your (great) project, I recognized following "issue". After processing a file/ CompilationUnit with the Java-Parser (even LexicalPreservation enabled) and printing it, the parser introduces or removes some line breaks as the following diff (created via Eclipse) shows:

![java-parser-diff](https://user-images.githubusercontent.com/25261696/34033919-9a652584-e17c-11e7-86e3-20e28d67cf27.PNG)
(Note: The first line in surrounding type is changed because it contained four space characters which are also not present anymore after processing it with the Parser. I'm not sure about this, actually the changes are fine IMO but in sense of lexical preservation might be also kept as was - or? What do you think?)

Actually it seems not to be such a big deal, but as we would like to use the parser to refactor some old code with and try to keep as much of formatting as before with every commit, it would be really nice to have this fixed - especially when it's no big deal for you to do so?

This would result in smaller diffs and fewer (formatting) changes for us. (We also restrict the usage of any additional CodeFormatter to a Minimum -> Just to the parts we greatly changed or newly introduced.)

I create the issue since I had not time to dig in deeper into this, but if I have I'll provide some updates on it - or even create a PR (my very first one). Thank you in advance!

**Comment by ftomassetti** [comment] 2017-12-15 18:58
First of all thank you for reporting this. If you would have time for a PR that would be great and we would help you in the process, otherwise we will look into this as soon as we can

**Comment by ftomassetti** [comment] 2018-01-14 08:21
Could you provide the code on which you noted this issue?

**Comment by ftomassetti** [comment] 2018-05-13 12:01
It could be hard to fix this without the original code (which I should have asked immediately). I would tend to close this issue because we have no way to reproduce it.

**Comment by matozoid** [comment] 2018-05-13 12:55
It could be because the poster configures the lexical preserving printer, then outputs with the pretty printer anyway.

**Closed as completed by matozoid** 2018-05-13 12:55 UTC
Labels: Bug report, Lexical Preservation
