### ISSUE TITLE
Using JSS and JP to compare shared resources

### ISSUE THREAD

**Issue by socketopp** [javaparser/javaparser#2142] opened 2019-03-27 11:19 UTC
I am trying to find out what variables and objects (resources) that are shared among functions in a class using the javaparser but it is a bit tedious because I have to iterate through all the functions and look if the resources used are first declared, if not look if any other functions use the same resources etc.

Is this possible or even easier with the help of the symbol-solver? How would I use it together with javaparser? (I have started out with javaparser and love it so far). 

So I am basically interested in ressolving the context of variables/object calls I guess? To see whether a variable is simply used or declared in a scope of a function? What would be desired is to fetch all resources for one function in which it has not declared and then simply compare these between all functions.

Unfortunately the lovely book on javaparser/symbol-solver mainly deals with resolving types so it did not give me any pointers on the use of contexts. I find the JSS to be much less straight forward to use than JP unfortunately. 

Any help regarding this matter is much appreciated. 
Thanks.

**Comment by matozoid** [comment] 2019-03-27 11:24
@ftomassetti ?

(I'm getting the feeling that we should not just return a resolved type or an exception, but a wrapper around it that tells you how it was solved. A bit like how the parser can return a `ParseResult`.)

**Comment by ftomassetti** [comment] 2019-03-28 15:29
First of all notice that JSS is now integrated in JP. You basically call `resolve` on a bunch of nodes and find their corresponding declaration.

The rest of the question is not super clear to me.

@matozoid the problem is that resolving a certain symbol would depend on resolving another symbol, so we should propagate the error in case we do not just throw an exception. What do you mean by explaining how it was solved?

**Comment by matozoid** [comment] 2019-03-28 15:55
@ftomassetti uhuh, not a small task. "How" means like "I couldn't find the type in the compilation unit, so I used this import and found the type through this solver in this jar."

**Comment by ftomassetti** [comment] 2019-03-28 16:15
Yes, that would be interesting to provide. Not trivial but quite interesting.

**Comment by socketopp** [comment] 2019-03-28 17:51
@ftomassetti @matozoid When I try to print node.resolve(). I get the following error:
`Exception in thread "main" java.lang.IllegalStateException: No data of this type found. Use containsData to check for this first.`
What does this exactly mean and what key should be used as parameter to containsData?

**Comment by ftomassetti** [comment] 2019-03-29 08:38
We should improve the error message there. I guess it is due to the fact that you did not configured symbol solving

**Comment by socketopp** [comment] 2019-03-29 11:15
@ftomassetti Ah, cheers, it must a very common beginner error. Thanks for the help. I managed to configure it with reflectionTypeSolver but not with javaParserTypeSolver which is important if I want the JSS to look for classes defined in source files.

I try to configure the JavaParserTypeSolver with the path to the src directory of my project. 
`TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(new File("WorkSpace/projectName/src/projectName/"));`
However I receive:
`Exception in thread "main" java.lang.NoClassDefFoundError: com/google/common/cache/CacheBuilder
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.<init>(JavaParserTypeSolver.java:58)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.<init>(JavaParserTypeSolver.java:87)
	at com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver.<init>(JavaParserTypeSolver.java:63)
`

What is causing this error? I am not too familiar with googles CacheBuilder.

**Comment by ftomassetti** [comment] 2019-03-29 13:46
NoClassDefFoundError seems due to a missing dependency. Right @matozoid ?

**Comment by socketopp** [comment] 2019-03-29 14:13
@ftomassetti @matozoid 
I got these jars files. Might be missing something? (I am aware that the prefered way is to use Gradle or Maven)
javaparser-core-3.10.0.jar
javaparser-symbol-solver-core-3.10.0.jar
javaparser-symbol-solver-model-3.10.0.jar
javaparser-symbol-solver-logic-3.10.0.jar

**Comment by ftomassetti** [comment] 2019-03-29 14:21
Yes, you are missing something. I think the issue here is that you are not familiar with Java. I suggest you look into that before working with an advanced framework as JP. Here you should know that these libraries have dependencies and those dependencies could have other dependencies. So you should really use gradle or maven instead of downloading JARs manually as there could be tens/hundreds of JARs to download and add to the path and an error is so easy to do.

**Comment by matozoid** [comment] 2019-03-31 15:50
Just for this case we have this sample setup: https://github.com/javaparser/javasymbolsolver-maven-sample

**Closed as completed** 2020-02-26 09:45 UTC
Labels: Question (JP usage), Symbol Solver
