### ISSUE TITLE
Static MethodCallExpr Resolving Problem

### ISSUE THREAD

**Issue by seoj135** [javaparser/javaparser#1491] opened 2018-04-03 14:35 UTC
Hello. When I tried to resolve methodcallexpr, I found some bug. 
This is on 3.5.20.

1. Call Static Function on Iterable, ForeachStmt problem.
MethodCallExprContext line 157: context return null. So It Throw RuntimeException
I guess some errors on solveType() function on StatementContext(Wrapped BlockStmt).
Here is target project from git: https://github.com/davidar/lljvm
and positions is src/lljvm/runtime/Function.java line 22.

```
TypeSolver Settings: 
   ReflectionTypeSolver
   JavaParserTypeSolver(Root of project)
   JavaParserTypeSolver(Root of Java base libraries, I zipped out it to my custom directory)
```

2. visit NameExpr problem.
So To find the solution to the first bug, I make some short code and found another bug.
How to fix UnsolvedSymbolException?
Why does not some nodes resolve? 
 !ref.isSolved() 

Here is my whole test code:
```java
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.expr.NameExpr;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import com.github.javaparser.resolution.declarations.ResolvedMethodDeclaration;
import com.github.javaparser.resolution.types.ResolvedType;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

public class test {
	@SuppressWarnings({ "unchecked", "rawtypes" })
	public static void main(String[] args) {
		String code = 
			"public class A { " + 
				"public int FUNC() { Class<?> cls = null; if(cls == null) return 0; else { B.FUNC3(cls); return 1;} } " +
				"public void FUNC2(Class<?> arg) { return; }" +
			"}" + 
			"class B {" + 
				"public static void FUNC3(Class<?> arg) { return; }" +
			"}" +
			"";
		File file = new File("A.java");
		try {
			file.createNewFile();
			FileWriter fw = new FileWriter(file);
			fw.write(code);
			fw.flush();
			fw.close();
		} catch (IOException e) {
			e.printStackTrace();
		}
		
		CombinedTypeSolver localCts = new CombinedTypeSolver();
		localCts.add(new ReflectionTypeSolver());
		localCts.add(new JavaParserTypeSolver(file.getAbsoluteFile().getParentFile()));
		
		ParserConfiguration parserConfiguration = new ParserConfiguration().setSymbolResolver(new JavaSymbolSolver(localCts));
		JavaParser.setStaticConfiguration(parserConfiguration);
		
		CompilationUnit cu = JavaParser.parse(code);
		cu.accept(new VoidVisitorAdapter() {
			public void visit(NameExpr n, Object arg) {				
				ResolvedType type = JavaParserFacade.get(localCts) .getType(n);
				super.visit(n, args);
			}
			public void visit(MethodCallExpr n, Object arg) {
				ResolvedMethodDeclaration decl = JavaParserFacade.get(localCts).solve(n).getCorrespondingDeclaration();
				super.visit(n, args);       // <---------- bug is occur.
                                // Exception in thread "main" UnsolvedSymbolException{context='Solving B', name='B', typeSolver=null}
			}
		}, null);
	}
}
```

**Comment by malteskoruppa** [comment] 2018-04-04 14:37
Concerning your second problem, I can answer the question. (But I don't know about the first problem you mentioned).

What's happening here is that in this part of your code:
```
public void visit(NameExpr n, Object arg) {				
	ResolvedType type = JavaParserFacade.get(localCts) .getType(n);
	super.visit(n, args);
}
```
...you are visiting the *scope* of the method call expression `B.FUNC3(cls);` within the function `A#FUNC()` of the code that you are parsing. This scope is a `NameExpr` with the name `B`.

You then try to resolve the type of the `NameExpr` with the name `B`. However, `B` is already a type. Java Symbol Solver (understandably) can't resolve the type of a type, so it throws the `UnsolvedSymbolException{context='Solving B', name='B', typeSolver=null}` that you are seeing.

If you only wish to resolve the called method, you can simply resolve the entire `MethodCallExpr` as you are already doing in your visit method for `MethodCallExpr`. Basically, just throw away your `visit` method for `NameExpr` and you'll be fine.

If, however, you _do_ wish to resolve the type of the scope, then **make sure** that you only try to do so when the scope is an expression that can be resolved to a type but *not* a type by itself. Unfortunately, JSS provides no way to distinguish these two cases. This is a known problem (see #1439, #1480 for ample discussions about this problem).

**Comment by malteskoruppa** [comment] 2018-04-04 19:48
Note: The above concerns only the second problem you mentioned in your original post. I don't know about the first problem. :-)

**Comment by seoj135** [comment] 2018-04-08 16:34
Ok. I Actually recognise what make a bug.
When trying to resolve some expressions like field access of a instance, method access of a instance, 
UnsolvedSymbolException is occurred.

**Comment by ftomassetti** [comment] 2018-07-08 09:58
Reading the first problem: [the indicated file](https://github.com/davidar/lljvm/blob/master/java/src/lljvm/runtime/Function.java) on line 22 has a blank line.

I am ignoring the first point and looking at the test code.

**Comment by ftomassetti** [comment] 2018-07-08 10:29
I think the issue here is that `getType` is invoked on the name of a type (as it is used on static field accesses). The problem is that `getType` was intended only to be used on values. So I changed it to allow to be used also on names of types because this seems a common misconception about that method.

**Comment by ftomassetti** [comment] 2018-07-08 10:30
Which by the way was what @malteskoruppa correctly figured out months ago :D

**Comment by ftomassetti** [comment] 2018-07-08 10:31
Removing bug report label as in my opinion is not a bug but it is clearly a confusing API that we should clarify and improve.

**Comment by matozoid** [comment] 2018-07-08 10:44
Isn't it more or less solved now?

**Comment by ftomassetti** [comment] 2018-07-08 11:28
Yes, my understanding is that we can merge the PR and then close this task

**Closed as completed** 2018-07-08 20:00 UTC
Labels: Improvement, Symbol Solver

**Comment by malteskoruppa** [comment] 2018-07-09 13:51
@ftomassetti Awesome, thanks for this! :-)

**Comment by ftomassetti** [comment] 2018-07-09 13:51
Thank you @malteskoruppa !
