### ISSUE TITLE
Getting a (Javadoc) Comment for a particular Method in a CompilationUnit?

### ISSUE THREAD

**Issue by kedarmhaswade** [javaparser/javaparser#273] opened 2016-02-18 22:56 UTC
Is it possible to get the (Javadoc) Comments associated with a Method definition/declaration in a CompilationUnit? I see that I can get all the Comments, but it is not clear how to associate a Comment with a Method. Perhaps the AST does not allow it?

**Comment by kedarmhaswade** [comment] 2016-02-19 03:43
Sorry, I figured it out using `CompilationUnit` and `MethodVisitor` that extends `VoidVisitorAdapter`. Thanks! But there is an issue. I think while parsing the line 215 in java/util/Comparator.java, javaparser throws an exception at column 31. The line in question:

```
    default Comparator<T> thenComparing(Comparator<? super T> other) {
        Objects.requireNonNull(other);
        return (Comparator<T> & Serializable) (c1, c2) -> { // this is the defaulting line
            int res = compare(c1, c2);
            return (res != 0) ? res : other.compare(c1, c2);
        };
    }
```

and the error shown by javaparser is:

```
Exception in thread "main" com.github.javaparser.ParseException: Encountered " "&" "& "" at line 215, column 31.
Was expecting one of:
    "boolean" ...
    "byte" ...
```

**Comment by ftomassetti** [comment] 2016-02-19 07:11
About the comment: Yes, visitor is the way to go in this case.

About the parse exception: Which version of JavaParser are you using? If you are not using version 2.3.0 try to update, I think we worked on that part of the grammar recently.

**Comment by kedarmhaswade** [comment] 2016-02-19 22:21
@ftomassetti thanks for the tip. I upgraded to use 2.3.0, but it does not seem to help. I get the same exception.

I have created a little project for you. It's ready to go and should easily help demo the test case. All you need is Java 8 installed and access to the src.zip from there.
1. Clone [https://github.com/kedarmhaswade/since-when](https://github.com/kedarmhaswade/since-when).
2. Run: `java -jar target/java-source-since-final.jar /tmp/src.zip Comparator`

Of course, it works like a charm for classes like `Collections.java`. Thanks!

**Comment by waqas19921** [comment] 2016-02-25 08:15
Please help can not get javaDoc comments through getJavaDoc() method for classorinterface declaration and method declaration.
i tested value 
/**
 *
- @author waqas
  */
  before class declaration and method declaration and returns null

**Comment by waqas19921** [comment] 2016-02-25 08:17
@ftomassetti you have written that this issue is passed here 
https://travis-ci.org/javaparser/javaparser/builds/111681156
but it is not

**Comment by ftomassetti** [comment] 2016-04-09 07:53
This error seems related to the Intersection Type. I tried parsing it with JavaParser 2.3.0 and it caused an exception. I then parsed it with JavaParser 2.4.0 and the exception is gone.

JavaParser 2.4.0 will be available soon and should solve this issue. Closing. Please reopen it if you find the issue is still present in version 2.4.0

**Closed as completed by ftomassetti** 2016-04-09 07:53 UTC
