### ISSUE TITLE
Solving generic types that are of type java.lang.Object

### ISSUE THREAD

**Issue by dhardtke** [javaparser/javaparser#1370] opened 2018-01-29 02:12 UTC
Sorry for the non-descriptive title, but I didn't come up with anything better...

Look at this code:

```java
final String source = String.join(System.lineSeparator(),
        "package graph;",
        "class Vertex<Data> {",
        "    private final Data data;",
        "    public Vertex(Data data) { this.data = data; }",
        "    public Data getData() { return this.data; }",
        "}",
        "",
        "public class Application {",
        "    public static void main(String[] args) {",
        "        System.out.println(new Vertex<>(42).getData().equals(42));",
        "    }",
        "}");

final JavaParserFacade facade = JavaParserFacade.get(new ReflectionTypeSolver(false));

JavaParser.parse(source).accept(new VoidVisitorAdapter<Void>() {
    @Override
    public void visit(final MethodCallExpr n, final Void arg) {
        super.visit(n, arg);

        try {
            System.out.printf("Node: %s, solved Type: %s%n", n, facade.solve(n));
        } catch (RuntimeException e) {
            e.printStackTrace();
        }
    }
}, null);
```

> Method 'equals' cannot be resolved in context new Vertex<>(42).getData().equals(42) (line: 10) MethodCallExprContext{wrapped=new Vertex<>(42).getData().equals(42)}. Parameter types: [PrimitiveTypeUsage{name='int'}]

How can I solve the chained `equals()` call? Doing this works:
```java
Integer d = new Vertex<>(42).getData();
System.out.println(d.equals(42));
```

But what about more complex cases, like this:

```java
public class Application<Data> {
    public static void main(String[] args, Data data) {
        System.out.println(data.equals(42));
    }
}
```

> Method 'equals' cannot be resolved in context data.equals(42) (line: 10) MethodCallExprContext{wrapped=data.equals(42)}. Parameter types: [PrimitiveTypeUsage{name='int'}]

Thanks!

**Comment by dhardtke** [comment] 2018-02-02 01:48
I noticed something interesting:
After replacing `class Vertex<Data> {` with `class Vertex<Data extends Object> {` the solving works...
I guess it is safe to assume `java.lang.Object` is always the supertype of a generic type, but I don't really know how the SymbolSolver works

**Comment by MysterAitch** [comment] 2020-01-21 12:08
I suspect that this issue was fixed in one of the recent versions of JavaParser which addressed resolving `Object` (I'm not able to reproduce with v3.15.9).

@dhardtke - could you take a look at this with a recent version of JavaParser and advise if this problem is still present please?

**Comment by dhardtke** [comment] 2020-01-21 21:07
If the above code I posted in the original post now works I must presume the bug is fixed.

I do not have access to the code that is using JavaParser anymore 😛

**Comment by MysterAitch** [comment] 2020-01-21 22:30
@dhardtke - Cheers! 

For the sake of completeness I'll upload the test case so that it can be double checked and then I can delete the local branch :) 

Feel free to close this if you're happy to do so! Otherwise, all being well, merging the pr will do it too.

**Closed as completed** 2020-01-22 13:33 UTC
Labels: Bug report, Symbol Solver
