### ISSUE TITLE
DumpVisitor wrong for Enums

### ISSUE THREAD

**Issue by cdietrich** [javaparser/javaparser#231] opened 2015-11-09 12:29 UTC
public enum ABC {} is serialized as public enum ABC implements {}

**Comment by ftomassetti** [comment] 2015-11-09 13:39
This is probably due to our recent adoptiion of lazily initialized lists: it was a massive refactoring which affected the whole codebase and we missed a few points, including this one.

Thank you for reporting this, we will fix this and add more tests.

**Comment by ftomassetti** [comment] 2015-11-09 13:46
This could have been fixed by #226 (which we just merged). Ideally we should still add the tests to prove that before closing this issue.

**Comment by cdietrich** [comment] 2015-11-09 19:16
yes and now. the import one is fixed. but there is a new one

```
package test; enum XYZ {}
```

gets

```
package test;

enum XYZ {

    ;
}
```

the empty statement should not be serialized

**Comment by ftomassetti** [comment] 2015-11-10 08:20
Thank you for reporting this. A PR has been proposed to address it (with a specific test to prevent regressions)

**Closed as completed** 2015-11-30 08:51 UTC
