### ISSUE TITLE
MethodCallExpr visitor & its child nodes

### ISSUE THREAD

**Issue by PELock** [javaparser/javaparser#3377] opened 2021-09-17 01:23 UTC
Hi, I'm using MethodCallExpr visitor to find a particular class call, but I'm a little bit surprised, it's triggered only ONCE for code like this

```java
system.out.println(sum(a,b));
```
and it lists call to `sum(a,b)` in its child nodes as a `MethodCallExpr` type, but it doesn't trigger a visitor on it, why not if it's of `MethodCallExpr` type? Thank you.

**Comment by jlerbsc** [comment] 2021-09-17 19:48
Hi @PELock can you give us a sample code you are using?

**Comment by PELock** [comment] 2021-09-17 20:09
I'm visiting classes/interfaces, and from each one I visit `MethodCallExpr`, I was sure this was working ok (was there anything changed?), I'm using parser core v3.22.1

```java
        compilation_unit.accept(new VoidVisitorAdapter<Void>()
        {
            @Override
            public void visit(ClassOrInterfaceDeclaration nodeClass, Void param)
            {
                nodeClass.accept(new VoidVisitorAdapter<Void>()
                {
                    @Override
                    public void visit(MethodReferenceExpr methodReferenceExpr, Void param)
                    {
                        ...
                    }

                }, null);

                nodeClass.accept(new VoidVisitorAdapter<Void>()
                {
                    @Override
                    public void visit(MethodCallExpr methodCallExpr, Void param)
                    {
			...
                    }
                }, null);

            }
	}, null);
```

**Comment by jlerbsc** [comment] 2021-09-21 14:41
I'm not sure to understand what you want to do but in each Overrided method, do you invoke the visit method in the parent class?

**Comment by PELock** [comment] 2021-09-21 15:04
As you can see I visit `MethodCallExpr` from `ClassOrInterfaceDeclaration` visitors, but the `MethodCallExpr` is only called once for

```java
system.out.println(sum(a,b));
```
Shouldn't it be called twice for `system.out.println()` and `sum()` calls?

**Comment by jlerbsc** [comment] 2021-09-21 17:00
You have to call super.visit(...) in each overrrided methods. Below an exemple 

     String sourceCode = "system.out.println(sum(a,b))";
        // Setup symbol solver
        ReflectionTypeSolver typeSolver = new ReflectionTypeSolver(false);
        ParserConfiguration configuration = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(new CombinedTypeSolver(typeSolver)));

        // Setup parser
        StaticJavaParser.setConfiguration(configuration);
        Expression expr = StaticJavaParser.parseExpression(sourceCode);

        expr.accept(new VoidVisitorAdapter<Void>() {
            @Override
            public void visit(MethodCallExpr methodCallExpr, Void param) {
                System.out.println(methodCallExpr.toString());
                **super.visit(methodCallExpr, param);** <-- this is what you have to add
            }
        }, null);

**Comment by PELock** [comment] 2021-09-21 17:05
I would expect a visitor would hit every instance of the type...? Is this the right design decision?

I mean other visitors like `MethodDeclaration` gets called for EVERY instance of `MethodDeclaration`, and here I need to call `super`?

**Comment by MysterAitch** [comment] 2021-10-05 11:34
Hi @PELock ,

It is a while since I used the visitors, but I understand @jlerbsc to be correct and that this to be by design.

Consider this example from page 12 of the ([free but donations welcomed](https://leanpub.com/javaparservisited)) ebook:

```java
    private static class MethodNamePrinter extends VoidVisitorAdapter<Void> {
    @Override
    public void visit(MethodDeclaration md, Void arg) {
        super.visit(md, arg);
        System.out.println("Method Name Printed: " + md.getName());
    }
}
```

And this paragraph on page 13:

> Although in this particular example it will not affect the behaviour of our visitor we make a call to
> super to ensure child nodes of the current node are also visited. This is typically recommended as
> additional visits accrue little overhead, however not visiting the whole tree is more likely inclined
> to result in unwanted behaviour.
> 


This is important for you, in your example but not the book's example, because a `MethodCallExpr` can be a child node of a `MethodCallExpr` (as opposed to the ebook's example of a method name - a method name cannot be a child of a method name).

The other part to note is whether you do the `super.visit()` at the start / end of the method as it will affect the order that you visit the nodes -- which may or may not be important to you.

Hope this helps!

**Comment by MysterAitch** [comment] 2021-10-05 11:47
I'm closing this now, but if you have any further questions feel free to re-open it or create a new post :+1:

**Closed as completed by MysterAitch** 2021-10-05 11:47 UTC
Labels: Question (JP usage)
