### ISSUE TITLE
JavaSymbolSolver unable to solve JDK classes inside a inner class implementing an interface

### ISSUE THREAD

**Issue by corradomio** [javaparser/javaparser#3103] opened 2021-02-20 10:39 UTC
Given the class

```
import java.util.List;

public class Test {
    public void test() {
        class Worker implements Runnable {
            private String jobs;
            List<String> tokens;
            public StringBuilder sb;

            public void run() {

            }
        }
    }
}
```

JSS is unable to solver ```String```, ```List<String>```, ```StringBuilder```
BUT, removing ```Runnable```, JSS works fine.

**Comment by 4everTheOne** [comment] 2021-02-20 12:37
Hello corradomio, i tried to reproduce the issue but i was unable to. I tried with the following unit test and it resolved with sucess:
```java
@Test
    void testIssue3103() {
        StaticJavaParser.getConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));

        String sourceCode = "import java.util.List;\n" +
                "\n" +
                "public class Test {\n" +
                "    public void test() {\n" +
                "        class Worker implements Runnable {\n" +
                "            private String jobs;\n" +
                "            List<String> tokens;\n" +
                "            public StringBuilder sb;\n" +
                "\n" +
                "            public void run() {\n" +
                "\n" +
                "            }\n" +
                "        }\n" +
                "    }\n" +
                "}\n";
        CompilationUnit cu = StaticJavaParser.parse(sourceCode);
        List<VariableDeclarator> variables = cu.findAll(VariableDeclarator.class);
        assertEquals(3, variables.size());

        assertEquals("java.lang.String",                    variables.get(0).getType().resolve().describe());
        assertEquals("java.util.List<java.lang.String>",    variables.get(1).getType().resolve().describe());
        assertEquals("java.lang.StringBuilder",             variables.get(2).getType().resolve().describe());
    }
```

Do you have any stack trace of it? Which type solvers were you using?

**Comment by corradomio** [comment] 2021-02-20 13:05
Very strange.
I am using my ""custom"" type solvers, BUT I am analyzing Deeplearning4J, composed by ~5800 java files and I found just a single case of this strange behavior.
I am using JP/JSS 3.19.0 + the patch for NameExpr (issue 3072).
I check if I obtain the same result using ""standard"" type solvers.
I don't use "ReflectionTypeSolver", but a "JarTypeSolver" collecting the JDK jars located in "[JAVA_HOME]/lib" and "[JAVA_HOME]/jre/lib"

**Comment by corradomio** [comment] 2021-02-20 13:39
1) I am using ""real source files""
2) 
```
private static void solve(File source) {
        CombinedTypeSolver ts = new CombinedTypeSolver();
        ts.add(new JavaParserTypeSolver(new File("src_only")));
        ts.add(new JarTypeSolver().addJdk(new File("D:\\Java\\Jdk8.0.x64")));

        ParseResult<CompilationUnit> result = pool.parse(source);
        result.ifSuccessful(cu -> {

            SolveSymbolsVisitor ssv = new SolveSymbolsVisitor();
            ssv.analyze(cu, ts);
        });
    }
```
Note: ```JarTypeSolver().addJdk(...)``` is a simple extension to ```JarTypeSolver``` to specify the JDK directory (<= 8.0) and to add automatically the content of "lib" and "jre/lib".
```SolveSymbolsVisitor``` is the visitor used to test the parser: I resolve the symbol, intercept the exception and dump it.

Same problem.
Obviously I have a list of files that I am checking, NOT just "Test". In another class, JSS resolve correctly "String" etc.

**Comment by corradomio** [comment] 2021-02-20 14:30
Update:
Using EXACTLY your code, I obtain the same result

```
Exception in thread "main" java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at com.github.javaparser.symbolsolver.javaparsermodel.declarations.JavaParserClassDeclaration.getAncestors(JavaParserClassDeclaration.java:357)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.checkAncestorsForType(JavaParserTypeDeclarationAdapter.java:117)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.JavaParserTypeDeclarationAdapter.solveType(JavaParserTypeDeclarationAdapter.java:99)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ClassOrInterfaceDeclarationContext.solveType(ClassOrInterfaceDeclarationContext.java:121)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveTypeInParentContext(Context.java:103)
	at com.github.javaparser.symbolsolver.core.resolution.Context.solveType(Context.java:93)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:668)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:645)
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.toResolvedType(JavaSymbolSolver.java:281)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:301)
	at com.github.javaparser.ast.type.ClassOrInterfaceType.resolve(ClassOrInterfaceType.java:60)
	at org.hls.check.CheckMini.test2(CheckMini.java:82)
	at org.hls.check.CheckMini.main(CheckMini.java:94)
```

If I comment out "Runnable" it works fine.
JP/JSS 3.19.0, JDK 1.8.0_281 x64

**Comment by jlerbsc** [comment] 2021-02-20 16:53
We can't help you with so little information. Please share more information.

**Comment by jlerbsc** [comment] 2021-02-20 17:12
The same unit test provided by @4everTheOne works perfectly. Please verify your application and try to isolate this issue.

**Comment by Col-E** [comment] 2021-02-20 18:29
> **I am using JP/JSS 3.19.0 + the patch for NameExpr (issue 3072).**
> I don't use "ReflectionTypeSolver", but a "JarTypeSolver" collecting the JDK jars located in "[JAVA_HOME]/lib" and "[JAVA_HOME]/jre/lib"

I can confirm in my branch for #3072 that this still works, so you may want to check out how your custom type resolver is implemented.

I added more checks to the case that @4everTheOne provided just in case.

```java
@Test
public void test3103() {
	StaticJavaParser.getConfiguration()
			.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));
	String sourceCode = "import java.util.List;\n" +
			"\n" +
			"public class Test {\n" +
			"    public void test() {\n" +
			"        class Worker implements Runnable {\n" +
			"            private String jobs;\n" +
			"            List<String> tokens;\n" +
			"            public StringBuilder sb;\n" +
			"\n" +
			"            public void run() {\n" +
			"\n" +
			"            }\n" +
			"        }\n" +
			"    }\n" +
			"}\n";
	CompilationUnit cu = StaticJavaParser.parse(sourceCode);
	List<VariableDeclarator> variables = cu.findAll(VariableDeclarator.class);
	assertEquals(3, variables.size());
	// Resolving as variables works
	assertEquals("java.lang.String",                    variables.get(0).getType().resolve().describe());
	assertEquals("java.util.List<java.lang.String>",    variables.get(1).getType().resolve().describe());
	assertEquals("java.lang.StringBuilder",             variables.get(2).getType().resolve().describe());
	// Resolving as types works too
	List<ClassOrInterfaceType> types = cu.findAll(ClassOrInterfaceType.class);
	assertEquals(5, types.size());
	assertEquals("java.lang.String",                    types.get(0).resolve().describe());
	assertEquals("java.util.List<java.lang.String>",    types.get(1).resolve().describe());
	assertEquals("java.lang.String",                    types.get(2).resolve().describe()); // In the generic type arg
	assertEquals("java.lang.StringBuilder",             types.get(3).resolve().describe());
	assertEquals("java.lang.Runnable",                  types.get(4).resolve().describe());
}
```

**Comment by jlerbsc** [comment] 2021-02-21 09:06
I close this issue because we cannot reproduce it with the same test case. You can comment on this issue again if you have additional information to enable us to reproduce the case.

**Closed as completed** 2021-02-21 09:06 UTC
