### ISSUE TITLE
Exception when parsing a String literal which contains /*

### ISSUE THREAD

**Issue by andreasschrade** [javaparser/javaparser#204] opened 2015-10-02 10:05 UTC
Hello all,

I really honor your great work and would just leave a small issue.
I get an exception when I try to parse the following snippet inside a method:

```
    mMatcher = new UriMatcher(UriMatcher.NO_MATCH);
    mMatcher.addURI(mAuthority, "tree/*/document/*", MATCH_DOCUMENT_TREE);
```

The snippet results in:

> java.lang.StringIndexOutOfBoundsException: String index out of range: -1
>   at java.lang.AbstractStringBuilder.deleteCharAt(AbstractStringBuilder.java:762)
>   at java.lang.StringBuffer.deleteCharAt(StringBuffer.java:378)
>   at japa.parser.ast.comments.CommentsParser.parse(CommentsParser.java:82)
>   at japa.parser.ast.comments.CommentsParser.parse(CommentsParser.java:23)
>   at japa.parser.JavaParser.insertComments(JavaParser.java:381)
>   at japa.parser.JavaParser.parse(JavaParser.java:94)
>   at japa.parser.JavaParser.parse(JavaParser.java:114)

It looks like that the (duplicated) occurence of "/*" breaks the javaparser.

Any feedback about that issue would be really really great.

Many thanks in advance.

Regards,
Andreas

**Comment by ftomassetti** [comment] 2015-10-02 10:40
Thank you for the nice words and for reporting the issue: it is really important for improving JavaParser.

I could not reproduce this issue with the current version from master and your stack trace report line _CommentsParser.java:23_ which currently is a blank line:

https://github.com/javaparser/javaparser/blob/master/javaparser-core/src/main/java/com/github/javaparser/ast/comments/CommentsParser.java#L23

I suspect you could be using a JavaParser different from the last one. Could you please try to update and see if the problem persists?

**Comment by andreasschrade** [comment] 2015-10-05 13:47
Thanks for your fast reply.
You are right! I updated to the latest release version and everything works fine now. 

Sorry for the false alarm.

Regards,
Andreas

**Comment by ftomassetti** [comment] 2015-10-05 15:28
No problem, I am happy you could solve this one!
I guess we can close this issue.

**Closed as completed by ftomassetti** 2015-10-05 15:28 UTC
