### ISSUE TITLE
JSS throws StackOverFlow exception when trying to resolve NameExpr

### ISSUE THREAD

**Issue by eartvit** [javaparser/javaparser#1879] opened 2018-10-10 13:53 UTC
Hi,
I am trying to find out if a NameExpr resolves to a primitive type or not. In general it finds out type with the exception of unchecked types.

For example, trying to find out the the resolved type for the IfStmt:
``if (ind != numSamples) { samples.set(ind, key); }``
on line 194 of InputSampler.java from Hadoop branch 3.0.0 always crashes (it enters an infinite loop on JavaParserFactory line 114:
``return getContext(parentNode, typeSolver);``

The complete input file (inside Hadoop branch 3.0.0) is hadoop-branch-3.0.0/hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapred/lib/InputSampler.java

Is there a way around this problem?

I am trying to resolve the type using the below approach:
``SymbolReference<? extends ResolvedValueDeclaration> rRef = JavaParserFacade .get(new ReflectionTypeSolver()).solve(n.getName());``
where n is the left or right expression of an IfStmt...

As I said, it works in all my other cases, except the above...

Thanks in advance for any advice or perhaps a bug fix?

**Comment by jlerbsc** [comment] 2020-10-23 13:33
In this example ind variable is an int and numSamples is a long (see https://github.com/apache/hadoop/blob/trunk/hadoop-mapreduce-project/hadoop-mapreduce-client/hadoop-mapreduce-client-core/src/main/java/org/apache/hadoop/mapred/lib/InputSampler.java). I cannot reproduce this issue with the test code below. I close this issue but you are free to reopen it if you encounter this problem again. But please can you provide us with a simplified test case which reproduces the error.

    @Test()
    void test() throws IOException {
        
        String src =
                "public class A {\n" + 
                "    public void m() {\n" + 
                "        long numSamples = 10L;\n" +
                "        // ...\n" +
                "        int ind = r.nextInt(numSamples);\n" + 
                "        if (ind != numSamples) {\n" + 
                "           samples.set(ind, key);\n" + 
                "        }\n" + 
                "    }\n" + 
                "}";

        ParserConfiguration config = new ParserConfiguration();
        config.setSymbolResolver(new JavaSymbolSolver(new ReflectionTypeSolver()));
        StaticJavaParser.setConfiguration(config);

        CompilationUnit cu = StaticJavaParser.parse(src);
        
        IfStmt is = cu.findFirst(IfStmt.class).get();
        BinaryExpr be = is.getCondition().asBinaryExpr();
        System.out.println(be.getLeft().calculateResolvedType().describe());
        System.out.println(be.getRight().calculateResolvedType().describe());
        assertEquals("int", be.getLeft().calculateResolvedType().describe());
        assertEquals("long", be.getRight().calculateResolvedType().describe());
    }

**Closed as completed by jlerbsc** 2020-10-23 13:33 UTC
Labels: Bug report, Symbol Solver
