### ISSUE TITLE
Parent of ClassOrInterfaceType node not set correctly?

### ISSUE THREAD

**Issue by mlangkabel** [javaparser/javaparser#574] opened 2016-11-18 12:34 UTC
I'm using the Javaparser to create an AST for the following snippet of code:
```java
public class JavaTest {
    public String[] field;

    public void foo(String[] arg){
    }
}
```

Now I'm using a visitor to print out the node hierarchy. In addition to the node class of each visited node I'm printing the class name of what the node believes to be its parent:
<pre>
 javaparser.ast.CompilationUnit parent: none...
 | javaparser.ast.PackageDeclaration parent: javaparser.ast.CompilationUnit
 | javaparser.ast.body.ClassOrInterfaceDeclaration parent: javaparser.ast.CompilationUnit
 | | javaparser.ast.body.FieldDeclaration parent: javaparser.ast.body.ClassOrInterfaceDeclaration
 | | | javaparser.ast.type.ClassOrInterfaceType parent: javaparser.ast.body.FieldDeclaration
 | | | javaparser.ast.body.VariableDeclarator parent: javaparser.ast.body.FieldDeclaration
 | | | | javaparser.ast.body.VariableDeclaratorId parent: javaparser.ast.body.VariableDeclarator
 | | javaparser.ast.body.MethodDeclaration parent: javaparser.ast.body.ClassOrInterfaceDeclaration
 | | | javaparser.ast.type.VoidType parent: javaparser.ast.body.MethodDeclaration
 | | | javaparser.ast.body.Parameter parent: javaparser.ast.body.MethodDeclaration
 | | | | javaparser.ast.type.ClassOrInterfaceType parent: <b>javaparser.ast.type.ArrayType</b>
 | | | | javaparser.ast.body.VariableDeclaratorId parent: javaparser.ast.body.Parameter
 | | | javaparser.ast.stmt.BlockStmt parent: javaparser.ast.body.MethodDeclaration
</pre>

What strikes me as odd is that the second `ClassOrInterfaceType` node has an `ArrayType` node stored as its parent (which is not even part of the AST) while the first one hasn't.

I think this must be a bug, right?

**Comment by matozoid** [comment] 2016-11-20 13:47
When I use this code:

``` java
package com.github.javaparser;

import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.type.ClassOrInterfaceType;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;

public class Xxx {
    public static void main(String[] args) {
        String code = "public class JavaTest {\n" +
                "    public String[] field;\n" +
                "\n" +
                "    public void foo(String[] arg){\n" +
                "    }\n" +
                "}";
        CompilationUnit compilationUnit = JavaParser.parse(code);

        compilationUnit.accept(
                new VoidVisitorAdapter<Void>() {
                    @Override
                    public void visit(ClassOrInterfaceType n, Void arg) {
                        System.out.println(n.getParentNode().get().getClass());
                    }
                }, null);
    }
}
```

I get

```
class com.github.javaparser.ast.body.FieldDeclaration
class com.github.javaparser.ast.body.Parameter
```

This is on the master branch. Which version are you using?

**Comment by mlangkabel** [comment] 2016-11-21 09:11
I was using 3.0.0-alpha.8, but I just tested this case after updating to the alpha.10 tag and now everything looks fine. Awesome!

**Comment by mlangkabel** [comment] 2016-11-21 09:32
Oh it seems like I posted this a little bit too early. The system I used to test this was not on the alpha.10 tag at all. I'll inform you as soon as I know more...

**Comment by matozoid** [comment] 2016-11-21 11:28
Okay, I'm not aware of this ever being a problem or getting fixed, so I'm curious what caused this :)

**Comment by mlangkabel** [comment] 2016-11-22 11:27
Ok, I did a lot of testing by now and it appear that you are right. There is nothing wrong with Javaparser :)

I'm working on the JavaSymbolSolver right now and it looks like solving parts of a method actually alters the AST (which it shouldn't). I'll continue looking in that direction right now, so i think we can close this issue. Thanks again for your quick responding @matozoid!

**Comment by matozoid** [comment] 2016-11-22 11:49
Thanks for the follow up! Good to know there is no issue :)

**Comment by mlangkabel** [comment] 2016-11-22 12:11
Haha, I think I found the real issue! Calling `Parameter.getType()` wraps the Parameter's elementType into an ArrayType and sets the generated ArrayType as the elementType's parent. This modification persists in the AST, even though it is not obvious to the user. Thus my question: Is this intended behavior?

To provide a simple example I just expanded your test code a little bit:

```java
package com.github.javaparser;

import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.Parameter;
import com.github.javaparser.ast.type.ClassOrInterfaceType;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;

public class Xxx {
    public static void main(String[] args) {
        String code = "public class JavaTest {\n" +
                "    public String[] field;\n" +
                "\n" +
                "    public void foo(String[] arg){\n" +
                "    }\n" +
                "}";
        CompilationUnit compilationUnit = JavaParser.parse(code);

        compilationUnit.accept(
                new VoidVisitorAdapter<Void>() {
                @Override
                public void visit(ClassOrInterfaceType n, Void arg) {
                        System.out.println(n.getParentNode().get().getClass());
                }
                @Override
                public void visit(Parameter n, Void arg) {
                        n.getType();
                	super.visit(n, arg);
                }
        }, null);
    }
}
```

I get:
```
class com.github.javaparser.ast.body.FieldDeclaration
class com.github.javaparser.ast.type.ArrayType
```

**Comment by matozoid** [comment] 2016-11-22 14:47
Cool, now we have a bug. No, this is not as intended. I think we can fix it by cloning elementType before wrapping it. Will do!

**Comment by matozoid** [comment] 2016-11-22 14:56
Background:
In change #237 you can see the whole thought process about ArrayTypes. You can see that I'm pretty relieved to finally find something that works ;) By now I'm starting to think that I shouldn't have gone through all the trouble to keep the brackets in the AST, because they are of little interest to people analysing code. So I'm contemplating a change where the bracket information is no longer the leading information that's stored in the AST (and getType uses that to construct the final type.) Then the AST would contain only the type, no more brackets.

**Comment by mlangkabel** [comment] 2016-11-22 15:23
I think cloning the elementType would be a good solution, except a user wants to manipulate that node and keep that manipulated node inside the AST. But on the other hand side Parameter.getType() may return an ArrayType node which has never been part of the AST in the first place. 

Oh, I've just seen there is also a Parameter.getElementType() method that just returns that field (which can be manipulated however the user likes).

So I' with you on cloning the elementType in this case :)

**Comment by matozoid** [comment] 2016-11-22 19:50
And would you vote for having brackets as AST element + a generated type, or the type as AST element?

**Comment by ftomassetti** [comment] 2016-11-22 20:20
I think it is important to know which methods would give back a generated node, i.e., a Node that is not part of the tree. In that case we would probably not use those methods in JavaSymbolSolver but use only nodes that are part of the AST because when a type is part of the AST I can figure out its context and use that to resolve type (e.g., navigate until the imports, figuring out that a name refer to an imported class, stuff like that)

**Comment by mlangkabel** [comment] 2016-11-22 21:27
So would removing the brackets from the AST mean that a user would have no way to get any info on the bracket locations?

**Comment by matozoid** [comment] 2016-11-22 21:40
Yes, in the case of parameters, you would only have the ArrayTypes around the type of each parameter left.

**Comment by mlangkabel** [comment] 2016-11-22 21:52
So the question actually is: Please choose one of the following.
* Use ArrayTypes that wrap some Type (which again can be an ArrayType) and the ArrayType stores the info on the brackets
* Store the bracket info inside whatever node is parent of the ArrayType (this may be a Parameter node)

In this case I'd choose the former option, because "having an array of arrays of stuff" feels more like a tree-like thing and not so much like a list to me. That's just my oppinion and I'm probably missing something that made you favor the latter option ;)

**Comment by matozoid** [comment] 2016-11-22 22:02
My reason was to keep information about the shape of the source code around. I think I made a mistake there, and am now looking for feedback to see if we should do more work :)

**Comment by matozoid** [comment] 2016-11-22 22:17
Anyway, fixed on master, fixed in next alpha.

**Comment by mlangkabel** [comment] 2016-11-23 06:44
Nice to hear that it's fixed.

Haha, we should always do more work ;) Hm, don't get me wrong. I also think that we should store the array information somewhere. When you're saying "keep information about the shape of the source code" do you mean, where the brackets are? In that case I'm totally with you, someone might need the information at some point.
I don't see why it's necessary to keep both representations (ArrayTypes and bracket lists) "available". Can't we use one kind of representation (I favor ArrayTypes) and use it everywhere? Or is there a reason why we need to keep both representations?

**Comment by matozoid** [comment] 2016-11-23 10:36
I see what you mean - the positive thing about having two representations is that in something like `int[] a[]` the int[] isn't a type you really want to use. So that's split up into "element type = int, brackets = [bracketpair]" with the idea that this information is only used when you ask for the type of a.

So would you suggest that we remove elementType (because this has no array information by definition) and put something else there (partialType?) so that `int[] a[]` gives "partialType = ArrayType(int), a = ArrayType(ArrayType(int))" ? This would lead to funky logic if we set a to not be an array at all, because we would have to modify partialType, and then we would have to look at all other variables in this definition (imagine `int[] a[], b, c[][]` and stating that a is now a simple int.) But it *would* fix the problem where the type is disconnected from the AST, which is a very tricky problem (and I do not want tricky stuff in JavaParser.)

**Comment by mlangkabel** [comment] 2016-11-23 14:10
Ok, now I'm starting to understand the real issue here. I `int[] a[], b, c[][]` the type info `int []` is (part of) the type of `a`, `b` and `c`. And if you ask `c` for its type it *needs* to construct an artificial node because the AST may store array information in a different way (for example in the case mentioned above part of the array information is stored in the `FieldDeclaration` while another part is stored in the `VariableDeclaratorId`. 

I'm quite new to Java but I've been working with C++and Clang ASTs a lot. So here is what they do: 

```c++
void test()
{
	int a[42], b;
}
```

This code generates the following part of an AST:

```
FunctionDecl [test] <1:1, 4:1>
| FunctionProtoTypeLoc <1:1, 1:11>
| | BuiltinTypeLoc <1:1, 1:1>
| CompoundStmt <2:1, 4:1>
| | DeclStmt <3:2, 3:14>
| | | VarDecl [a] <3:2, 3:10>
| | | | ConstantArrayTypeLoc <3:2, 3:10>
| | | | | BuiltinTypeLoc <3:2, 3:2>
| | | | | IntegerLiteral <3:8, 3:8>
| | | VarDecl [b] <3:2, 3:13>
| | | | BuiltinTypeLoc <3:2, 3:2>
```

So as you see Clang does not store any type information inside the DeclStmt (which could be the FieldDeclaration in Javaparser) but instead stores the type information inside the VarDecl nodes for `a` and `b`. Of course this is duplicate information but it must be much simpler to handle so that the Clang developers found it to be worth the effort ;)

Do you think that there is anything preventing us to do it in the same way?

**Comment by matozoid** [comment] 2016-11-23 14:50
This shows that they didn't care to store information about where exactly the braces are. We can indeed do this, and this is what I was considering, and what you have given me good arguments for. So thanks for the information: this is very helpful!

As an aside: this means I can also kill `EmptyImportDeclaration`, because who cares about that in an AST anyway? :)

**Comment by mlangkabel** [comment] 2016-11-23 14:58
Haha, go, kill it! I mean having it makes kind of sense, but it does not provide any relevant information. So from my perspective as a user of the Javaparser we don't need it.

By the way, I think we can close this issue now ;)

**Comment by matozoid** [comment] 2016-11-23 15:15
Cool, thanks!

**Closed as completed by matozoid** 2016-11-23 15:15 UTC
Labels: Bug report
