### ISSUE TITLE
JSS can't resolve complicated generic method

### ISSUE THREAD

**Issue by HoldYourWaffle** [javaparser/javaparser#1964] opened 2018-12-13 11:13 UTC
I found another generics choke, could be related to #1945.
Because the issues are probably related I have updated the old [sample project](https://github.com/HoldYourWaffle/JavaParserGenericsChoke) instead of creating a new one.

The scenario is as follows: we have a `Message` and a `MessageHandler<REQ, RES>` interface. The `REQ` parameter means the type of request the handler can handle, `RES` is the type of `Message` it sends back.
The choke happens when I try to parse calls to the following method:
```java
public <REQ extends Message, REP extends Message> void registerMessage(Class<? extends MessageHandler<REQ, REP>> messageHandlerType, Class<REQ> requestMessageType)
```
Yeah it's not pretty... Sadly I can't change this api.

I hope this is enough information.

**Comment by matozoid** [comment] 2018-12-13 12:20
Choke? :-)

**Comment by HoldYourWaffle** [comment] 2018-12-13 12:39
That api code is worth choking on

**Comment by matozoid** [comment] 2018-12-17 19:30
Looks reasonable to me. And it's a good challenge for the symbol solver. But can you change the description to something more useful?

**Comment by HoldYourWaffle** [comment] 2018-12-18 17:50
Yeah I was pretty tired when I made this...

**Comment by jlerbsc** [comment] 2024-02-08 21:01
I'm closing this issue because no further information has been provided and we don't know how to reproduce the problem.

**Closed as completed by jlerbsc** 2024-02-08 21:01 UTC
Labels: Bug report, Symbol Solver, Minimal testcase wanted
