### ISSUE TITLE
JavaSymbol Solver is not able to resolve args of simple method callexpression

### ISSUE THREAD

**Issue by mr-rajeshrathod** [javaparser/javaparser#2205] opened 2019-04-30 19:43 UTC
JavaParser is not able to resolve simple method call expression for me. I am trying to resolve the expression.

This is happening for some of the specific types of method call only and rest are working fine.  I have confirmed that concerned classes and jars are loaded in TypeResolver.

I am attaching sample java program that can help the team to reproduce this issue. Please look into MyTest.Java (<PROJECT_ROOT>/src/main/resources) that we are trying to parse and get the method call expression.

Can someone please help with this issue?

**Java Parser Version**: 3.13.10

**Exception:**
I have confirmed that servlet-api is loaded in JarTypeResolver.
```
Caused by: javassist.NotFoundException: javax.servlet.http.HttpServletRequest
	at javassist.ClassPool.get(ClassPool.java:422)
	at javassist.bytecode.Descriptor.toCtClass(Descriptor.java:571)
	at javassist.bytecode.Descriptor.getParameterTypes(Descriptor.java:424)
	at javassist.CtBehavior.getParameterTypes(CtBehavior.java:323)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistMethodDeclaration.getNumberOfParams(JavassistMethodDeclaration.java:119)
	... 53 more

```
**Code that throws an exception**
MethodResolutionLogic and line #373. It's lambda expression so unable to debug it.

Attachment is an eclipse based maven project.
[javaparser-maven-sample.zip](https://github.com/javaparser/javaparser/files/3132871/javaparser-maven-sample.zip)

Download following jars and copy into **C:/temp/jars**
http://central.maven.org/maven2/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.jar
http://central.maven.org/maven2/javax/portlet/portlet-api/2.0/portlet-api-2.0.jar
http://central.maven.org/maven2/com/liferay/portal/portal-service/6.1.20/portal-service-6.1.20.jar

**Comment by matozoid** [comment] 2019-05-01 08:15
Thanks for the report!

**Comment by mr-rajeshrathod** [comment] 2019-05-01 12:25
Thanks @matozoid. Any idea when you have the plan to fix this?

**Comment by matozoid** [comment] 2019-05-01 12:45
Hi @mr-rajeshrathod - I won't fix this. This part of the library is looking for a new maintainer.

**Comment by jlerbsc** [comment] 2020-11-03 13:52
Hi @mr-rajeshrathod can you check you have always this issue with the lastest JP version and provide us a simple unit test. Thanks.

**Comment by jlerbsc** [comment] 2021-06-28 13:52
This issue cannot be reproduced with the test project because it doesn't contains external libraries.

**Comment by matozoid** [comment] 2021-06-29 07:12
@jlerbsc he mentions the required external libraries - does it need more?

**Comment by maartenc** [comment] 2021-06-29 11:16
I think the issue might already have been resolved with PR #3167

**Comment by jlerbsc** [comment] 2021-06-29 11:45
@matozoid That's enough, I didn't have to pay attention to it, but it's very easy and quick to have a project that works without having to download or install libraries.

**Comment by matozoid** [comment] 2021-06-29 11:47
Well, I doubt @mr-rajeshrathod is still working on it, so if nobody takes the time to investigate, best close it :-)

**Comment by jlerbsc** [comment] 2021-07-01 06:06
This issue seems to be solved in the JP current version. The test case below needs some setup. We have to download dependencies in the directory  src/test/resources/issue2205


    @Test
    void test() throws IOException {

        String code = "import com.liferay.portal.kernel.util.ParamUtil;\n" +
                "import javax.portlet.RenderRequest;\n" +
                "public class MyTest {\n" +
                "    public void hello(RenderRequest request) {  \n" +
                "        String ssn = ParamUtil.getString(request, \"ssn\");\n" +
                "        String custId = (String) request.getAttribute(\"custId\");\n" +
                "        System.out.println(\"Customer Details are \" + ssn + \", \" + custId);\n" +
                "    }\n" +
                "}";

        Path pathToJar1 = adaptPath("src/test/resources/issue2205/servlet-api-3.0-alpha-1.jar");
        Path pathToJar2 = adaptPath("src/test/resources/issue2205/portlet-api-2.0.jar");
        Path pathToJar3 = adaptPath("src/test/resources/issue2205/portal-service-6.2.1.jar");

        ParserConfiguration config = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(
                        new CombinedTypeSolver(new ReflectionTypeSolver(), new JarTypeSolver(pathToJar1),
                                new JarTypeSolver(pathToJar2), new JarTypeSolver(pathToJar3))));

        StaticJavaParser.setConfiguration(config);

        CompilationUnit cu = StaticJavaParser.parse(code);

        cu.accept(new VoidVisitorAdapter<Void>() {

            @Override
            public void visit(MethodCallExpr n, Void arg) {
                ResolvedMethodDeclaration md = n.resolve();
                System.out.println(n.getNameAsString() + " -> " + md.getClassName());
            }

        }, null);
    }


Result is

    getString -> ParamUtil
    getAttribute -> PortletRequest
    println -> PrintStream

**Closed as completed by jlerbsc** 2021-07-01 06:06 UTC
Labels: Bug report, Symbol Solver, Need test case
