### ISSUE TITLE
MethodReferenceExpr was not parsed properly

### ISSUE THREAD

**Issue by 4everTheOne** [javaparser/javaparser#3077] opened 2021-02-10 17:11 UTC
If we try to parse a lambda function that uses a `ThisExpr` or `NameExpr` as scope it shows in the tree as `TypeExpr`.

As an example lets use the following code:
```java
List<Object> copy = new ArrayList<>();
List<Object> items = new ArrayList<>();
items.forEach(copy::add);
```

In this code snippet we are just making a copy of the list with lambdas. 

When the parser tries to parse `copy::add` he assumes it's going to be a `TypeExpr` instead of a `ThisExpr` or `NameExpr` resulting in a wrong structure like the diagram below. The diagram only shows the line `items.forEach(copy::add);`.

![Diagram](https://user-images.githubusercontent.com/5434488/107543162-d9637980-6bc0-11eb-9206-f96cd24b2635.png)

As we can see, in the bottom right we have the identifier copy, which should be a `NameExpr` instead of `TypeExpr`.

I think the root of the issue is related with the JavaCC at this part of the code:
https://github.com/javaparser/javaparser/blob/dd3785d398225fdf41375a8672d18fdd47966112/javaparser-core/src/main/javacc/java.jj#L3593-L3597

This issue may also be related with #2455.

## Unit test for the issue
```java
@Test
void test() {
  String sourceCode = "import java.util.List;\n" +
                      "import java.util.ArrayList;\n" +
                      "\n" +
                      "class A {\n" +
                      "  void method() {\n" +
                      "    List<Object> copy = new ArrayList<>();\n" +
                      "    List<Object> items = new ArrayList<>();\n" +
                      "    items.forEach(copy::add);\n" +
                      "  }\n" +
                      "}";
  CompilationUnit cu = StaticJavaParser.parse(sourceCode);
  MethodReferenceExpr methodArgument = cu.findFirst(MethodReferenceExpr.class).get();
  assertTrue(methodArgument.findFirst(NameExpr.class).isPresent());
}
```

**Comment by MysterAitch** [comment] 2021-03-24 01:36
I'm not sure what it *should* return, but it's not _necessarily_ a type in the same way that a type isn't necessarily a class or interface (hence `ClassOrInterface`).

The problem seems to be caused by not knowing during the parse stage what the thing on the left hand side is (e.g., it could be `this` or a variable (`NameExpr`) or a type -- i.e. it's ambiguous.

I'll have a closer look after some sleep 😴😴


Edit: see also #3102

**Comment by jlerbsc** [comment] 2024-06-24 12:47
I'm closing this issue because at compile time, it's not possible to determine whether the declared type is a class vs interface (vs record).

**Closed as completed by jlerbsc** 2024-06-24 12:47 UTC
Labels: Bug report, JavaCC

**Comment by johanneskloos** [comment] 2025-04-11 16:07
@jlerbsc I have a hackish way of resolving this issue using a post-processing pass, which I'd be happy to contribute in cleaned-up form, but I'd like some architectural guidance.

As said in the issue description, the underlying issue is that we always parse dotted names (i.e., names of the form `A.B.C.d`) as type references, even though they may well be references to fields or variables. As you said, we cannot differentiate between these situations in the parser code.

But if we have access to a `TypeSolver`, once we have a fully-parsed AST, we can "straighten out" there references: at a minimum, if we have a `MethodReferenceExpr` `expr` with a scope given by a `TypeExpr` of a `ClassOrInterfaceType` `type`, we can check whether `type` does, in fact, refer to a field or variable instead, using the following rules:
- If `type` is a simple name, and the name resolves to a field or variable in the context of `expr`, we should have a `NameExpr` instead.
- If `type` is of the form `scope.name` and scope actually refers to a variable of field, say `varOrField`, we should have a `FieldAccessExpr(varOrField, name)` instead
- If `type` is of the form `scope.name` and scope refers to a type that has a visible static field called `name`, we should have a `FieldAcessExpr(TypeExpr(scope), name)` instead (compare JLS 6.5.2 about obscuring: "the rules of [§6.5.2](https://docs.oracle.com/javase/specs/jls/se21/html/jls-6.html#jls-6.5.2) specify that a variable will be chosen in preference to a type, and that a type will be chosen in preference to a package.").
- Otherwise, we keep the `TypeExpr`.

Question 1 is whether this sounds right to you.

Question 2 is how this should plug into JavaParser:
1. The minimum solution would be to provide a clean-up visitor that users can run as required.
2. We could run this before calling `resolve`-type methods, but that would mean that resolution mutates the AST - probably not what we want?
3. We could make this a post-processing pass for the parser, if a `TypeSolver` is given.
4. As a variation, we could add another method to `SymbolResolver` (to classify a name in a given context - at least check whether it's a variable or field reference vs. a type reference) and make this a post-processing task if a `SymbolResolver` is given.

What is the best point of plugging this in? I'm tempted to go with the last option.

Question 3 is how widely we should scope this:
1. At a minimum, we should replace references in `MethodReferenceExpr`.
2. We could also "straighten out" all `TypeExpr`s that should actually be field accesses, regardless of context.
3. Moreover, sometimes we parse static variable accesses such as `java.lang.System.in` as a sequence of field accesses; we could also straighten out these accesses at the same time.

In my mind, option 2 would be sensible, and option 3 would help us get really clear ASTs. What would you prefer?

**Comment by jlerbsc** [comment] 2025-04-11 20:39
First of all, thank you for this proposition.
At present, everything that has been done on the project is based on the principle of not creating a dependency between the parser and the symbol resolution. Unfortunately, the solution you're proposing doesn't respect this principle. I don't have any other ideas but I'm open to other proposals.

**Comment by johanneskloos** [comment] 2025-04-11 21:15
Hm, I _think_ there is a way to achieve this: We have a `SymbolResolver` interface in `javaparser-core`. We could add one method to that interface, say:
```
/**
 * Does the expression {@code scope.name} (if {@code scope} is non-null) respectively {@code name}, in the context of
 * {@code context}, refer to a variable or static field?
 */
public boolean isReferenceToVariableOrStaticField(@Nullable TypeExpr type, String name, Node context);
```
In that way, we are not introducing any new coupling between the modules; all we'd have to do is to implement this method in `JavaSymbolSolver`, which is straightforward since we have a `TypeSolver` there. The only possible problem I see is that this may break any hypothetical other implements of `SymbolResolver` - do those exist?

**Comment by jlerbsc** [comment] 2025-04-12 07:27
It's true that you shouldn't introduce a dependency with an implementation of the symbol resolver, but what I really wanted to say is that not all JP users necessarily use symbol resolution, some only use the parser functions. With this solution there would automatically be a dependency on a symbol resolver even if it isn't used. This is not an option.

**Comment by johanneskloos** [comment] 2025-04-12 07:37
Right, I apologize for the misunderstanding. In that case, I'd suggest going with a significantly reduced solution: I'd provide a `ReferenceStraighteningVisitor` (name open for discussion) that implements the algorithm proposed above, and forget about any integration as a parser post-pass. So, basically, in those use cases where a user would care about whether something is a `TypeExpr` vs. a `FieldAccessExpr`, they'd run this visitor on their AST before further analysis. Suggested interface:
```
public class ReferenceStraighteningVisitor extends ModifierVisitor<Void> {
  public ReferenceStraighteningVisitor(TypeSolver typeSolver) { ... }
  // ...
  // Some convenience methods so that the user won't have to add casts themselves
  public Expression straighten(Expression e) {
    return (Expression)e.accept(this, null);
  }

  public <T extends Statement> T straighten(T e) {
    return (T)e.accept(this, null);
  }

  public <T extends BodyDeclaration> T straighten(T e) {
    return (T)e.accept(this, null);
  }

 // etc.
}
```

This code would then live in `javaparser-symbol-solver-core`, in some yet to be chosen package. Clearly not a perfect design, but the best I can come up with given the constraints of the project.

**Comment by johanneskloos** [comment] 2025-04-12 07:44
Actually, would you be totally opposed to changing `ParserConfiguration` a bit so that the user can request additional post-processors? In that way, we could have at least a bit of both worlds: `ReferenceStraighteningVisitor` could also provide a post-processor that can be *optionally* added to a parser configuration. In that way, we avoid an implicit dependency while still making it easy to configure Javaparser so that this bug is avoided.
