### ISSUE TITLE
bug resulted from Boolean.FALSE and false

### ISSUE THREAD

**Issue by MornSunShine** [javaparser/javaparser#2739] opened 2020-06-29 11:22 UTC
JavaParserFacade.solveMethodAsUsage throw exception,
when solving source code "Filters.eq(SearchableField.TRASHED, false)",
the former is "SearchableMetadataField<Boolean>",
the latter is boolean.
However, for type variable, boolean and java.lang.Boolean can be considered as same type.
when matchTypeParameters, the exception is thrown.

**Comment by MornSunShine** [comment] 2020-06-30 13:34
Many similar bug,like
String and CharSequence
int, long, boolean, ... vs Integer, Long, Boolean

**Comment by jlerbsc** [comment] 2020-09-25 13:45
Hi @MornSunShine , i cannot reproduce your issue with this test case. Could you provide us an improvement of it?

    void test() throws FileNotFoundException {
        String s = 
                "public class Foo {" +
                "  public void m() {" + 
                "    b(1);" +
                "    b(true);" +
                "    b(Boolean.TRUE);" +
                "  }" +
                "  public void b(Integer i) { "+
                "  }"+
                "  public void b(long l) { "+
                "  }"+ 
    //                "  public void b(Boolean b) { "+
    //                "  }"+
                "  public void b(boolean b) { "+
                "  }"+
                "}";
        CompilationUnit cu = parse(s);
        List<MethodCallExpr> mces = cu.findAll(MethodCallExpr.class);
        assertTrue("Foo.b(long)".equals(mces.get(0).resolve().getQualifiedSignature()));
        assertTrue("Foo.b(boolean)".equals(mces.get(1).resolve().getQualifiedSignature()));
        assertTrue("Foo.b(boolean)".equals(mces.get(2).resolve().getQualifiedSignature()));
    }

**Comment by MornSunShine** [comment] 2020-09-30 04:52
I'm sorry for the late reply.
I found the bug when I parse one android project files.
Firstly, the project is OK.
When I parse the code block, one exception is threw as the following:
```
    private void getBackupsFromDrive(DriveFolder folder) {
        AlertDialog.Builder b = new AlertDialog.Builder(this);
        String s = "aaa";
        b.setTitle(s);
        getResources().getString(R.string.preferences_experimental_title);
        b.setTitle(getResources().getString(R.string.preferences_experimental_title));
    }
```
The Exception as:
```
Exception in thread "main" java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call. Method call: b.setTitle(getResources().getString(R.string.preferences_experimental_title)), Parameter: getResources().getString(R.string.preferences_experimental_title)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:264)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:279)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solve(JavaParserFacade.java:143)
	at Test.main(Test.java:198)
Caused by: java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:657)
	at java.util.ArrayList.get(ArrayList.java:433)
	at com.github.javaparser.resolution.MethodUsage.getParamType(MethodUsage.java:150)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.isMoreSpecific(MethodResolutionLogic.java:688)
	at com.github.javaparser.symbolsolver.resolution.MethodResolutionLogic.findMostApplicableUsage(MethodResolutionLogic.java:724)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistUtils.getMethodUsage(JavassistUtils.java:89)
	at com.github.javaparser.symbolsolver.javassistmodel.JavassistClassDeclaration.solveMethodAsUsage(JavassistClassDeclaration.java:141)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.ContextHelper.solveMethodAsUsage(ContextHelper.java:48)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:190)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:440)
	at com.github.javaparser.symbolsolver.javaparsermodel.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:123)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:701)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:287)
	at com.github.javaparser.symbolsolver.javaparsermodel.TypeExtractor.visit(TypeExtractor.java:64)
	at com.github.javaparser.ast.expr.MethodCallExpr.accept(MethodCallExpr.java:115)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:526)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.getType(JavaParserFacade.java:358)
	at com.github.javaparser.symbolsolver.javaparsermodel.JavaParserFacade.solveArguments(JavaParserFacade.java:260)
	... 3 more
```
I parsed the code file with the following code:
```
        CompilationUnit cu = StaticJavaParser.parse(targetFile);
        ArrayList<Node> list1 = new ArrayList<>();
        list1.add(cu);
        List<MethodCallExpr> temp1 = Classifier.getAllNodes(list1, MethodCallExpr.class);
        for(MethodCallExpr methodCallExpr:temp1){
            System.out.println(
                    JavaParserFacade.get(typeSolver).solve(methodCallExpr)
                            .getCorrespondingDeclaration().getQualifiedSignature());
        }
```
Partial effective output is the following:
```
android.support.v7.app.AlertDialog.Builder.setTitle(java.lang.CharSequence)
android.content.res.Resources.getString(int)
android.support.v7.app.AppCompatActivity.getResources()
```

**Comment by MornSunShine** [comment] 2020-09-30 04:55
I try to solve the bug. I found two context to solve the TypeExtractor. One is Ok, and the other failed. However, I have no enough time to solve the bug thoroughly.

**Comment by jlerbsc** [comment] 2020-09-30 13:44
@MornSunShine Could you confirm that stacktrace is not related to the issue previously declared "bug resulted from Boolean.FALSE and false". It would be easier to help you if we had a usable test case.

**Comment by jlerbsc** [comment] 2024-02-07 09:38
I'm closing this door because we can't try to solve a problem that we don't know how to test.
If you can provide a simple test case then you can reopen this issue.

**Comment by MornSunShine** [comment] 2024-02-07 09:38
好的，邮件已收到，会尽快回复

**Closed as completed by jlerbsc** 2024-02-07 09:38 UTC
