### ISSUE TITLE
Cannot resolve `var` which has no initializer.

### ISSUE THREAD

**Issue by pjcuser** [javaparser/javaparser#3725] opened 2022-10-24 17:35 UTC
The problem is that javaparser cannot parse types declared with 'var'. 

Here's the test sample:

```
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.StaticJavaParser;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.body.MethodDeclaration;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.ast.visitor.VoidVisitor;
import com.github.javaparser.ast.visitor.VoidVisitorAdapter;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.model.resolution.TypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

class ParseTest {
    public void ParseMethods(File Path) throws FileNotFoundException {

        JavaCodeParser p = new JavaCodeParser(Path);
        p.getMethodDetails();

    }
}

public class Main {

    public static void main(String[] args) throws FileNotFoundException {
        ParseTest parseTest = new ParseTest();
        parseTest.ParseMethods(new File("src\\MyClass.java"));
    }
}

class JavaCodeParser {

    // Root of AST; and StaticJavaParser is a simple parser class.
    private CompilationUnit cu;

    JavaCodeParser(File JavaSourceFilePath) throws FileNotFoundException {

        CombinedTypeSolver combinedSolver = new CombinedTypeSolver();

        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();
        TypeSolver javaParserTypeSolver = new JavaParserTypeSolver(
                "src");

        combinedSolver.add(reflectionTypeSolver);
        combinedSolver.add(javaParserTypeSolver);

        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedSolver);
        StaticJavaParser.getConfiguration().setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_15);
        StaticJavaParser.getConfiguration().setSymbolResolver(symbolSolver);

        cu = StaticJavaParser.parse(new FileInputStream(JavaSourceFilePath));
    }

    public void getMethodDetails() {

        // This visitor will collect all method names into a list.
        VoidVisitor<Void> methodNameCollector = new MethodDetailCollector();

        // Execute visitor; note that instead of 'null' now its a 'method
        methodNameCollector.visit(cu, null);

    }

    private class MethodDetailCollector extends VoidVisitorAdapter<Void> {

        @Override
        public void visit(MethodDeclaration md, Void arg) {

            super.visit(md, arg);

            try {

                // Get information on method calls in body
                md.accept(new MethodCallVisitor(), arg);

            } catch (Exception e) {
                System.out.println(e);
            }
        }
    }

    private class MethodCallVisitor extends VoidVisitorAdapter<Void> {

        @Override
        public void visit(MethodCallExpr n, Void arg) {

            super.visit(n, arg);

            String MethodCallObjectType;
            String MethodCallName;

            try {
                if (n.hasScope()) {
                    MethodCallObjectType = n.getScope().get().calculateResolvedType().describe();
                } else {
                    MethodCallObjectType = "this";
                }
                MethodCallName = n.getNameAsString();
            } catch (Exception e) {
                System.out.println("Exception occurred: " + n.getName() + ": " + e);
            }
        }
    }
}
```

The files used for parsing:

**Account.java**

```
import java.util.ArrayList;
import java.util.List;

public class Account {
    
    public Account(int id, String accountName, double accountValue) {
        this.id = id;
        this.accountName = accountName;
        this.accountValue = accountValue;
    }

    private int id;
    private String accountName;
    private double accountValue;
    
    private List<Account> accountList = new ArrayList<Account>();

    void insertAccountIntoList(Account account) {
        accountList.add(account);
    }
    
    List<Account> getAccountList() {
        return accountList;
    }
    
    void printInfo() {
        System.out.println("id: " + id);
        System.out.println("accountName: " + accountName);
        System.out.println("accountValue: " + accountValue);
    }
}
```

**MyClass.java**

```
public class MyClass {
    
    public static void main(String[] args) {
        Account a = new Account(1, "AD1", 545.7);
        Account b = new Account(2, "AD2", 656.6);
        
        var accounts = a.getAccountList();
        accounts.add(a);
        accounts.add(b);
        
        for (var account : accounts) {
            account.printInfo();
        }
    }
}
```

The error is following:

`Exception occurred: printInfo: java.lang.IllegalStateException: Cannot resolve 'var' which has no initializer.`

The error occurs when I try to parse method body of main function for method calls inside it. How can I solve it?

**Comment by davidlinse** [comment] 2022-10-26 16:32
Maybe a duplicate of #3728 ?

**Comment by pjcuser** [comment] 2022-10-26 16:34
No, that one is not my issue. I am already using JAVA 10+ i.e. 15 and it doesn't work.

Also, please test my code and help me to correct this.

Thanks.

**Comment by jlerbsc** [comment] 2022-10-26 17:00
Hi @pjcuser I reduced your test case for testability but i cannot reproduce your issue.

    @Test
    void test1() {
        // Source code
        String sourceCode =
                "import java.util.ArrayList;\n"
                + "import java.util.List;\n"
                + "public class MyClass {\n"
                + "        \n"
                + "        public static void main(String[] args) {\n"
                + "            Account a = new Account();\n"
                + "            var accounts = a.getAccountList();\n"
                + "            accounts.add(a);\n"
                + "        }\n"
                + "        \n"
                + "        public class Account {\n"
                + "            public Account() {}\n"
                + "            private List<Account> accountList = new ArrayList<Account>();\n"
                + "            List<Account> getAccountList() {\n"
                + "                return accountList;\n"
                + "            }\n"
                + "        }\n"
                + "    }";
                
                
        // Setup symbol solver
        ParserConfiguration configuration = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(new CombinedTypeSolver(new ReflectionTypeSolver())));
        configuration.setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_15);
        // Setup parser
        JavaParser parser = new JavaParser(configuration);
        CompilationUnit cu = parser.parse(sourceCode).getResult().get();
        // Test
        cu.findAll(MethodCallExpr.class).forEach(mce -> {
            String MethodCallObjectType;
            if (mce.hasScope()) {
                MethodCallObjectType = mce.getScope().get().calculateResolvedType().describe();
            } else {
                MethodCallObjectType = "this";
            }
            String MethodCallName = mce.getNameAsString();
            System.out.println(MethodCallName);
            System.out.println(MethodCallObjectType);
        });
    }

This test case gave me this result


    getAccountList
    MyClass.Account
    add
    java.util.List<MyClass.Account>

**Comment by pjcuser** [comment] 2022-10-26 17:43
Hi,

Can you please at least test it on my source code that I have posted?

I modified your sample just to include my source code file and rest is the same and I am still getting exception:

```
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.nio.charset.StandardCharsets;

import org.apache.commons.io.FileUtils;

import com.github.javaparser.JavaParser;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.model.resolution.TypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.JavaParserTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

public class Test {
    
    public static void main(String[] args) throws IOException {
        test1();
    }
    
    static void test1() throws IOException {
        
        String fileName = "C:/src/MyClass.java";
        String content = FileUtils.readFileToString(new File(fileName), StandardCharsets.UTF_8);
        
        TypeSolver javaParserTypeSolver = new JavaParserTypeSolver( "C:/src");

        CombinedTypeSolver combinedSolver = new CombinedTypeSolver();
        TypeSolver reflectionTypeSolver = new ReflectionTypeSolver();
        
        combinedSolver.add(reflectionTypeSolver);
        combinedSolver.add(javaParserTypeSolver);

        JavaSymbolSolver symbolSolver = new JavaSymbolSolver(combinedSolver);
        
        // Setup symbol solver
        ParserConfiguration configuration = new ParserConfiguration().setSymbolResolver(symbolSolver);
        configuration.setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_15);
        // Setup parser
        JavaParser parser = new JavaParser(configuration);
        CompilationUnit cu = parser.parse(content).getResult().get();
        // Test
        cu.findAll(MethodCallExpr.class).forEach(mce -> {
            String MethodCallObjectType;
            if (mce.hasScope()) {
                MethodCallObjectType = mce.getScope().get().calculateResolvedType().describe();
            } else {
                MethodCallObjectType = "this";
            }
            String MethodCallName = mce.getNameAsString();
            System.out.println(MethodCallName);
            System.out.println(MethodCallObjectType);
        });
    }
}
```

### **Output:**

getAccountList
Account
add
java.util.List<Account>
add
java.util.List<Account>
Exception in thread "main" java.lang.IllegalStateException: Cannot resolve `var` which has no initializer.

**Comment by jlerbsc** [comment] 2022-10-26 19:15
> Can you please at least test it on my source code that I have posted?

I will call you back if necessary and answer your questions about my free time. It's time that I don't devote to my family.

**Comment by pjcuser** [comment] 2022-10-26 19:28
Sure. I understand as I have family too. So, I'll make it easier for you.

All you need to test is the following sample code. It's the same one you posted but I added a "for loop" in it inside source code.

```
import com.github.javaparser.JavaParser;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;

public class Test2 {
    
    void test() {
        // Source code
        String sourceCode =
                "import java.util.ArrayList;\n"
                + "import java.util.List;\n"
                + "public class MyClass {\n"
                + "        \n"
                + "        public static void main(String[] args) {\n"
                + "            Account a = new Account();\n"
                + "            var accounts = a.getAccountList();\n"
                + "            accounts.add(a);\n"
                + "                                              \n"
                + "            for (var account : accounts) {\n"
                + "                   account.test();\n"
                + "            }\n"
                + "        }\n"
                + "        \n"
                + "        public class Account {\n"
                + "            public Account() {}\n"
                + "            private List<Account> accountList = new ArrayList<Account>();\n"
                + "            List<Account> getAccountList() {\n"
                + "                return accountList;\n"
                + "            }\n"
                + "            public void test() {}\n"
                + "        }\n"
                + "    }";
                
                
        // Setup symbol solver
        ParserConfiguration configuration = new ParserConfiguration()
                .setSymbolResolver(new JavaSymbolSolver(new CombinedTypeSolver(new ReflectionTypeSolver())));
        configuration.setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_15);
        // Setup parser
        JavaParser parser = new JavaParser(configuration);
        CompilationUnit cu = parser.parse(sourceCode).getResult().get();
        // Test
        cu.findAll(MethodCallExpr.class).forEach(mce -> {
            String MethodCallObjectType;
            if (mce.hasScope()) {
                MethodCallObjectType = mce.getScope().get().calculateResolvedType().describe();
            } else {
                MethodCallObjectType = "this";
            }
            String MethodCallName = mce.getNameAsString();
            System.out.println(MethodCallName);
            System.out.println(MethodCallObjectType);
        });
    }
    
    public static void main(String[] args) {
        Test2 t2 = new Test2();
        t2.test();
    }
}

```

### Output:

getAccountList
MyClass.Account
add
java.util.List<MyClass.Account>
Exception in thread "main" java.lang.IllegalStateException: Cannot resolve `var` which has no initializer.

**Comment by jlerbsc** [comment] 2022-10-26 20:28
I think the problem comes from the for loop. There is a bug on how the var type is resolved in this case.
For the moment i don't know how to resolve this issue.

**Comment by pjcuser** [comment] 2022-10-28 16:29
Okay, let me know when this issue gets resolved. This is probably the only one stopping right now to properly parse java code. Thank you.

**Comment by abego** [comment] 2022-11-25 09:57
I think I ran into the same problem. 

I stripped the sample code even further and made it a JUnit test. Feel free to use it...

```
import com.github.javaparser.JavaParser;
import com.github.javaparser.ParserConfiguration;
import com.github.javaparser.ast.CompilationUnit;
import com.github.javaparser.ast.expr.Expression;
import com.github.javaparser.ast.expr.MethodCallExpr;
import com.github.javaparser.symbolsolver.JavaSymbolSolver;
import com.github.javaparser.symbolsolver.resolution.typesolvers.ReflectionTypeSolver;
import org.junit.jupiter.api.Test;


/**
 * see <a href="https://github.com/javaparser/javaparser/issues/3725">
 * https://github.com/javaparser/javaparser/issues/3725</a>
 */
public class CannotResolveVarWhichHasNoInitializerTest {

    @Test
    void cannotResolveVarWhichHasNoInitializer() {
        String sourceCode = "" +
                "public class Main {\n" +
                "    public static void main(String[] args) {\n" +
                "        for (var s : args) {\n" +
                "            s.toString();\n" +
                "        }\n" +
                "    }\n" +
                "}\n";

        // Parse the source code with Java 15 (and ReflectionTypeSolver)
        JavaSymbolSolver symbolResolver =
                new JavaSymbolSolver(new ReflectionTypeSolver());
        JavaParser parser = new JavaParser(new ParserConfiguration()
                .setSymbolResolver(symbolResolver)
                .setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_15));
        CompilationUnit cu = parser.parse(sourceCode).getResult().get();

        // find the "s.toString()" call inside the for loop
        MethodCallExpr toStringCall = cu.findAll(MethodCallExpr.class).stream()
                .filter(mce -> mce.getNameAsString().equals("toString"))
                .findFirst().get();
        Expression toStringCallScope = toStringCall.getScope().get();

        // The next line fails with
        // "java.lang.IllegalStateException: Cannot resolve `var` which has no initializer."
        toStringCallScope.calculateResolvedType();
    }
}
```

**Comment by abego** [comment] 2022-11-26 10:46
@jlerbsc FYI: I started working on this issue.

**Comment by abego** [comment] 2022-11-28 06:44
@jlerbsc regarding PR https://github.com/javaparser/javaparser/pull/3768: can you, as a maintainer, please approve for me as a first time contributor running workflows on Github? Thanks.

<img width="834" alt="Screenshot 2022-11-28 at 07 41 39" src="https://user-images.githubusercontent.com/696535/204210815-5b84aa3d-59d0-463c-b1af-39de2e0238ac.png">

**Closed as completed** 2022-11-28 11:25 UTC
Labels: Bug report, Symbol Solver

**Comment by pjcuser** [comment] 2022-11-28 12:43
Hi, I am author of this thread. So, can I download latest version of javaparser and it will work?

**Comment by jlerbsc** [comment] 2022-11-28 13:07
Hi, it is available in the snapshot version. The next version will not be released until January 2023

**Comment by pjcuser** [comment] 2022-11-28 13:15
Sorry, I don't understand github terminology. Does it mean I can download https://github.com/javaparser/javaparser/archive/refs/heads/master.zip and start testing/using it?

**Edit:** It sounds like a keyword in 'maven' dependency e.g. 0.1-SNAPSHOT. Can I know what maven dependency code I must use?

**Comment by jlerbsc** [comment] 2022-11-28 15:42
You need to clone and build the current version.
