### ISSUE TITLE
fail if a type is defined in a JAR, but implements an interface defined in another JAR

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1771] opened 2018-08-18 19:14 UTC
See #362 and #1851

**Comment by jlerbsc** [comment] 2020-10-18 16:22
This issue is probably linked to issue #2762

**Comment by JonasKvarnstrom** [comment] 2020-11-21 09:14
(Apologies in advance if I'm adding this to the wrong issue.  There seem to be many interlinked issues with similar problems.)

(Edited: Referenced the wrong class; should be com.github.javaparser.symbolsolver.javassistmodel.JavassistConstructorDeclaration)

I have a similar issue with many student projects that I am trying to analyze.  

For example, many projects use MigLayout which uses two separate JAR files:  miglayout-core-5.2.jar and miglayout-swing-5.2.jar.  If n is the ObjectCreationExpr corresponding to `new MigLayout()` and I call n.resolve(), then this fails with a (wrapped) NotFoundException.  

Tracing the error in a debugger shows the following (though I'm not an expert in understanding javaparser code):

* We arrive at ConstructorResolutionLogic.findMostApplicable()
* The first line needs to call isApplicable for all constructors
* The isApplicable() method first checks constructor.hasVariadicParameter() -> calls getNumberOfParams()
* In getNumberOfParams() there is a call to getParameterTypes() which actually wants to resolve the types, instead of just counting them (changing getNumberOfParams() to not resolve types unnecessarily could actually get rid of *some* of the exceptions even though it doesn't fix the root cause, and it seems like it would be easy to verify that this patch would be correct)
* In com.github.javaparser.symbolsolver.javassistmodel.JavassistConstructorDeclaration.getNumberOfParams(), the JavassistConstructorDeclaration has a complete typeSolver with 4 elements, a ReflectionTypeSolver and two JarTypeSolvers, but this information seems to be lost on the call to CtConstructor.getParameterTypes(), which only has a DeclaringClass with a ClassPool that only has access to the JAR file of the MigLayout constructor plus an AppClassLoader
* So CtConstructor.getParameterTypes() calls Descriptor.getParameterTypes() specifying declaringClass.getClassPool(), which calls toCtClass() -> ClassPool.get() in a ClassPool that does NOT have access to the other JAR file where a *parameter type* (net.miginfocom.layout.LC) is defined. 
* The parameter type can't be resolved, it isn't possible to determine which MigLayout(...) constructor is the most applicable one, and resolution fails.

I'm not sure if this means the JAR file containing the MigLayout class is wrong (that it should somehow explicitly specify that it is dependent on the other JAR file where the MigLayout constructor parameter class is defined), or if the complete typeSolver should be used when resolving the parameter types, or what else could be wrong in my own setup or in JavaParser.  I do know the project works well in IntelliJ IDEA.

**Comment by jlerbsc** [comment] 2020-11-21 17:05
This is an old issue on which no one has decided, for the moment, on the strategy to adopt. @MysterAitch an idea?

**Comment by jlerbsc** [comment] 2020-11-21 17:38
> * In getNumberOfParams() there is a call to getParameterTypes() which actually wants to resolve the types, instead of just counting them (changing getNumberOfParams() to not resolve types unnecessarily could actually get rid of _some_ of the exceptions even though it doesn't fix the root cause, and it seems like it would be easy to verify that this patch would be correct)

Javassists CtConstructor doesn't have another method to get the number of parameters. :-(

**Comment by MysterAitch** [comment] 2020-11-21 17:48
I'm not sure I understand the question/issue.

Is there any particular reason that one jar containing an implementation of an interface in a separate jar is a problem? 

For example, if I include the android (or the JavaParser) libraries as a JAR file then implement an interface from either then that is fine iirc. Ditto for the Log4J implementations where Log4J defines the interface but many other jars can implement it.

Maybe I'm missing something?

**Comment by jlerbsc** [comment] 2020-11-21 18:02
There are cases where we try to resolve something in a jar but there is a dependency with another object declared in another jar but JarTypeSolver can only access classes declared in the jar associated with it.

**Comment by MysterAitch** [comment] 2020-11-21 18:17
So... Just to spell out a scenario:

> JavaParser is used to analyse Project A (sources added for type solving). 
> 
> On Java 11 (reflection typesolver).
> 
> And... Project A has a dependency on Project B (added via jar typesolver).
> 
> And... Project B has a dependency on Project C (added via jar typesolver).

Which results in a problem because project B's typesolver can't access project C's types..?

- I know that the combined typesolver iterates through all typesolvers when trying to solve types. 

- I also recall that the typesolvers can have a parent / child structure. Not sure if this is used in practice though.

- Given this, my expectation is that the typesolver would attempt to solve it and then pass the request to the parent solver if unsuccessful. If that parent is a combined typesolver, iterate through the ones it "knows" about.

Assuming that this spells things out correctly (big assumption!), maybe that gives a hint/pointer re: where to look if that's not what is going on? 

e.g. would I be naive to suggest that maybe the solution is to ensure that the combined typesolver is used rather than an individual one? _...or perhaps that's the entire point of this GitHub issue in that this is what's being attempted but is buggy? :D_

**Comment by JonasKvarnstrom** [comment] 2020-11-21 18:47
I'm not sure if I'm using the correct JavaParser terminology here.  What I'm doing is the following.

I have an IntelliJ IDEA project where I have access to the sources of that project.  The project also uses two distinct MigLayout JAR files, `miglayout-core-5.2.jar` and `miglayout-swing-5.2.jar`.

In IntelliJ IDEA, I can run the project without any problems by adding the two JAR files to the project structure.  I can also run the program from the command line by making sure that both `miglayout-core-5.2.jar` and `miglayout-swing-5.2.jar` are in the CLASSPATH.

When I started using JavaParser and the symbol solver, I looked at some examples and came up with some code that uses a CollectionStrategy to collect sources and JAR files from the project folder.  I have verified that this results in a typeSolver that seems to have access to all the sources *and* all the classes in the JAR files.  This seems to work perfectly fine when the *sources* access classes in any of the JAR files.

But the JAR files also reference classes that are included in other JAR files.  Each JAR is not self-contained; it refers to classes in the standard Java class libraries (which is fine) but also to classes in other JAR files.  In the example in question, classes in miglayout-swing-5.2.jar refer to classes in miglayout-core-5.2.jar.

When code in the *source* refers to "new MigLayout()", it correctly finds all the MigLayout constructors in MigLayout.class in miglayout-swing-5.2.jar.  But the MigLayout constructors also refer to classes that are defined in miglayout-core-5.2.jar, such as net.miginfocom.layout.LC.  When you get to JavassistConstructorDeclaration.getNumberOfParams(), the complete type solver for the project is available, and if this type solver was used, you should be able to find net.miginfocom.layout.LC correctly.

Instead, getNumberOfParams() does the following:

```
    public int getNumberOfParams() {
        try {
            return ctConstructor.getParameterTypes().length;
        } catch (NotFoundException e) {
            throw new RuntimeException(e);
        }
    }
```

When I trace this in the debugger, the ctConstructor is of type javassist.CtConstructor, which extends CtBehavior, which extends CtMember, which stores its own declaringClass (a CtClass).  We get to this code:

```
    /**
     * Obtains parameter types of this method/constructor.
     */
    public CtClass[] getParameterTypes() throws NotFoundException {
        return Descriptor.getParameterTypes(methodInfo.getDescriptor(),
                                            declaringClass.getClassPool());
    }
```

Here the declaringClass already has its own class pool, and this class pool only has access to classes from the *same* JAR file and what I assume are classes from the built-in Java libraries.  The debugger shows that declaringClass.classPool.source is a ClassPoolTail with a pathList containing a JarClassPath for the miglayout-swing-5.2.jar file and a LoaderClassPath for "jdk.internal.loader.ClassLoaders$AppClassLoader@3d4eac69".  The path for miglayout-core-5.2.jar is *not* part of the source list here.

So when getParameterTypes() recurses down to Descriptor.getParameterTypes(), to Descriptor.toCtClass(), and to ClassPool.get(), it isn't possible to resolve the net.miginfocom.layout.LC type that is used as one constructor parameter, as this is only found in miglayout-core-5.2.jar.

So as far as I can tell (and again I'm new to these libraries), this is a separate Javassist form of resolution that does not directly use the JavaParser TypeSolver.  It uses some other form of ClassPool internal to Javassist, which currently lacks some of the path information.

**Comment by JonasKvarnstrom** [comment] 2020-11-21 19:10
So CtMember gets its declaringClass in the CtMember constructor.  This information is forwarded from CtBehavior(), which gets it from CtConstructor().

Since I don't understand the JavaParser code structure, I set a couple of breakpoints.  This shows that when I have a ResolvedReferenceType and call getTypeDeclaration().get(), the result is a JavassistClassDeclaration for a ctClass that has a classPool with the "limited" ClassPool.

Another breakpoint in the JavassistClassDeclaration constructor shows that the ctClass comes from JavassistFactory.toTypeDeclaration(), and then from JarTypeSolver.tryToSolveType():

```
    public SymbolReference<ResolvedReferenceTypeDeclaration> tryToSolveType(String name) {
        try {
            if (classpathElements.containsKey(name)) {
                return SymbolReference.solved(
                        JavassistFactory.toTypeDeclaration(classpathElements.get(name).toCtClass(), getRoot()));
            } else {
                return SymbolReference.unsolved(ResolvedReferenceTypeDeclaration.class);
            }
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
```

So the actual ctClass is `classpathElements.get(name).toCtClass()`, where `classpathElements.get(name).toCtClass()` is a ClassPathElement and toCtClass() is as follows:

```
        CtClass toCtClass() throws IOException {
            try (InputStream is = jarFile.getInputStream(entry)) {
                return classPool.makeClass(is);
            }
        }
```

So the classPool that is used comes from the JarTypeSolver.  In addPathToJar, we have the following:

```
    private void addPathToJar(String pathToJar) throws IOException {
        try {
            classPool.appendClassPath(pathToJar);
            classPool.appendSystemPath();
        } catch (NotFoundException e) {
            throw new RuntimeException(e);
        }
        JarFile jarFile = new JarFile(pathToJar);
        JarEntry entry;
        Enumeration<JarEntry> e = jarFile.entries();
        while (e.hasMoreElements()) {
            entry = e.nextElement();
            if (entry != null && !entry.isDirectory() && entry.getName().endsWith(".class")) {
                String name = entryPathToClassName(entry.getName());
                classpathElements.put(name, new ClasspathElement(jarFile, entry));
            }
        }
    }
```

The first few lines say that the ClassPool should only contain the path to *this* JAR file and the system path. 

Later on, this ClassPool is used inside Javassist to try to find classes that are *used* by the classes in the JAR.  For example, we have a JarTypeSolver for miglayout-swing, and when we start working with MigLayout inside miglayout-swing, this class uses the LC class from miglayout-core.  Then javassist can't find this class in its ClassPool.

As I understand it, recursive processing does not come into play in this particular case because we are dealing with code inside Javassist which only looks in a single incomplete ClassPool.

**Comment by MysterAitch** [comment] 2020-11-21 20:43
Thank you for the detailed helpful comments @JonasKvarnstrom (here and elsewhere)!

You're correct that JavaParser doesn't do the JAR side of things (instead we rely on javassist). Given that the compiled `.class` files within a jar don't expose as much information as the sources they're handled separately.

It sounds like there's a potential can of worms to open if we start adding class paths between JARs, though it sounds like that's what might be needed to actually fix it? 

Or perhaps there's a javassist exception that can be caught in the case of resolution failure, where we can retry using any of the other known / available typesolvers to enable cross-solver resolution? 

_sidenote: which directions work vs not work? -- e.g. can an interface provided in source code be resolved via the JARs? or is it just JAR-JAR that fails?_

**Comment by JonasKvarnstrom** [comment] 2020-11-22 07:24
> It sounds like there's a potential can of worms to open if we start adding class paths between JARs, though it sounds like that's what might be needed to actually fix it?

Again I'm not so familiar with the internals of JavaParser or Javassist, but it does look like that to me.

> Or perhaps there's a javassist exception that can be caught in the case of resolution failure, where we can retry using any of the other known / available typesolvers to enable cross-solver resolution?

I don't think so.

The problem arises when you are using Javassist to find out information about a class in JAR-based classpath entry A, and that class references a class in classpath entry B, where B is different from A and B isn't the path appended by appendSystemPath (which seems to be the system class path of the Java process/thread running Javassist).  

Example:

You resolve a constructor declaration to get a ResolvedConstructorDeclaration.  For MigLayout, which comes from a JAr file, the result happens to be a `JavassistConstructorDeclaration`.  The caller doesn't necessarily know about this.

You call `getNumberOfParams()` to find out more about the constructor.  This happens to be a method in `JavassistConstructorDeclaration`, which simply wants to return `ctConstructor.getParameterTypes().length`.  

The javassist `ctConstructor` was already created with an incomplete javassist `ClassPool`.  When you call its `getParameterTypes` method, it wants to use that internal ClassPool to find the actual class definitions for the parameters.  One parameter of `MigLayout()` is of type `LC`, which can't be accessed through the `ClassPool`.  Therefore it fails with a `NotFoundException`, which JavaParser wraps in a `RuntimeException`.

The `NotFoundException` can be caught (which is done) but I can't see a way to recover from it.  The "top-level" entity, the `MigLayout` constructor, was already resolved to a JavassistConstructorDeclaration and this had to happen through *this* JarTypeSolver using JarTypeSolver.tryToSolveType().  The JavassistConstructorDeclaration already had its ctConstructor specified, and it's the correct ctConstructor.

We can't even construct a set of multiple CtConstructor objects, both referring to the same constructor but having different ClassPools.  The same CtConstructor may have parameters of multiple types that come from multiple different JAR files, and a single call to getParameterTypes() must be able to find all of time.  The same is true for method parameters and I expect it to be true for classes that implement interfaces or extend classes from other/multiple JARs, and so on.

So as far as I can tell, the call to CtConstructor.getParameterTypes(), and many other methods, has to be done to a CtConstructor whose ClassPool has access to all relevant classes at the same time.
 
> _sidenote: which directions work vs not work? -- e.g. can an interface provided in source code be resolved via the JARs? or is it just JAR-JAR that fails?_

Now that you mention it, I expect that even if the ClassPool is changed so it has access to all already compiled files, Javassist will *still* fail in some cases.  The following seem to be the Javassist-based resolved entities:

```
JavassistAnnotationDeclaration
JavassistAnnotationMemberDeclaration
JavassistClassDeclaration
JavassistConstructorDeclaration
JavassistEnumConstantDeclaration
JavassistEnumDeclaration
JavassistFieldDeclaration
JavassistInterfaceDeclaration
JavassistMethodDeclaration
JavassistParameterDeclaration
JavassistTypeDeclarationAdapter
JavassistTypeParameter
```

Most of these have access to a Ct[Something] that provides a ClassPool and they expect that ClassPool to have access to *all* relevant classes.

So I expect that if a JavassistFieldDeclaration has a type that is specified in uncompiled source code, the JavaParser TypeSolver will be able to find that type but the corresponding CtField won't, because the field type can't be accessed through a ClassPool  Then there will still be failures.

But I also expect that the vast majority of all current failures are due to having JARs that refer to each other, and that it will be much less common that a JAR full of compiled files will refer "backwards" to classes for which we only have source.  In other words, it should be worth the effort to try extending the ClassPools with additional paths somehow.

By the way, MigLayout is far from the only place where this happens.  I believe it also happens in JavaFX libraries, for example.

**Comment by jlerbsc** [comment] 2020-11-22 10:08
@MysterAitch , @maartenc made some interesting remarks on the issue issue #2762

**Comment by JonasKvarnstrom** [comment] 2020-11-28 07:23
After I've thought a bit more about this, it seems to me that the perfect match for the JavaParser symbol solver would be a library that works more like the JavaParser source parser, but on bytecode -- in other words, something that gives you the *names* of all classes in a JAR file, the names of all methods in each class, the names of the parameter types and return types for those methods, and so on.  

Of course it would still be great if you got the *fully qualified* names instead of the code having to resolve everything -- this might even be the only way to do it, since resolving unqualified names is probably not possible when you don't have the import statements and the exact structure of the original source code.  But as long as you always got the *names*, you could then pass those names back up through the JavaParser symbol solver methods and handle them in a way that is more similar to what you currently do for information you get from the JavaParser AST.  After all, the symbol solver already has all the machinery for resolving things and finding the appropriate class definitions that *it* wants, on the symbolsolver level, in its list of TypeSolvers.

Unfortunately (?), Javassist seems to be designed with the fundamental assumption that you always want everything to be *fully* resolved.  When you call ctMethod.getParameterTypes(), the return value isn't an array of fully qualified parameter names (which would have been completely possible to handle).  It's an array of CtClass objects, which requires actually finding the class bytecode, which must then be available as compiled bytecode in the ClassPool of the CtClass that declares the CtMethod that we are currently interested in.  This seems to be a fundamental assumption, that you have a single ClassPool that you can use to access all the bytecode for all the classes referred to by any bytecode in the ClassPool (it's closed under class references).

If I understand things correctly, having a bytecode library that parses bytecode *superficially*, and only returns fully qualified class names instead of resolving to complete class definitions, would actually be the most complete solution for JavaParser.  This would result in a more consistent design where the bytecode "parsing" library is on exactly the same level as the JavaParser AST generation, and where the JavaParser symbol solver is on top of this.  It would allow:

- References from source to classes specified as bytecode, just like now

- References from bytecode classes to other bytecode classes in the same library, just like now

- References from bytecode classes to other bytecode classes in other libraries, because the references would only be resolved if and when this was required, and at that point we would have returned back all the way to a place where the CombinedTypeSolver would be used

- References from bytecode classes back to classes defined in source code, just as in the previous point.

And the second best thing would be to use a single ClassPool for all JarTypeSolvers, which should at least allow all JarTypeSolver class libraries to access each other. (Assuming there's no need for separation across different modules or anything.  I'm not really up to date on modern Java modules.)  This still wouldn't allow bytecode to refer to classes in source code, due to the mismatch in assumptions and structure between Javassist and JavaParser.

But maybe I've missed something, such as JavaParser using javassist in more ways than I've accounted for.

**Comment by mr-rajeshrathod** [comment] 2021-01-15 16:14
Hey guys, Is there any way to fix this issue? I am also hitting a similar problem in my project which is kind of blocker for us.

**Comment by MysterAitch** [comment] 2021-03-07 17:56
Apologies @jlerbsc -- looks like my bad merge earlier made the test suite (incorrectly) pass, which means I need to revert the PR in #3134 and reopen this issue.

See #3148 for the PR where this revert is happening.

**Comment by jlerbsc** [comment] 2021-03-07 18:16
Hi @MysterAitch could you tell me why did you revert "Use a singleton javassist classpool to fix issue #1771 and all related issues #362 and #1851". Is there a problem with this modification?

**Comment by MysterAitch** [comment] 2021-03-07 18:24
Yes, of course @jlerbsc -- apologies I didn't include more of a description before. 

See the two commits within #3148 -- note that the build/test for first commit (which reverts only the junit pioneer change) fails, but it passes after _also_ reverting #3134

I didn't get very far with debugging, but there was strange behaviour when testing locally that I suspect to be related to singleton/static shared state use -- specifically many tests would fail when running the test suite, while running tests individually would pass.

This was not picked up by the test suites is because `mvn test` would report that it was successful, despite the log reporting that tests failed to run. See #3147 for additional notes about this.

**Comment by MysterAitch** [comment] 2021-03-07 18:39
@jlerbsc -- I have just added more detail within #3134 , and I am about to merge #3151 which will (hopefully) prevent maven from (misleadingly) building successfully when tests are not run

While I am reasonably confident in my interpretations of the logs, Please do correct me if I have misunderstood anywhere! :+1:

**Comment by jlerbsc** [comment] 2021-03-07 19:41
> to be related to singleton/static shared state use

It's strange because all tests passed in my environment.
To resolve the exception "org.junit.platform.commons.util.UnrecoverableExceptions" i had to downgrade the junit-jupiter- * dependency version

**Comment by MysterAitch** [comment] 2021-03-07 20:19
@jlerbsc - Sounds like I might have been mistaken in my haste to get a release prepared, sorry!

Could you try submitting it again, perhaps? 

I don't mind doing it but want it (correctly) attributed to you :+1:

**Comment by jlerbsc** [comment] 2021-03-08 09:00
Hi @MysterAitch I don't know why i don't see the problem before i pushed the PR #3134 . It's my fault and now i understood what happens. Some tests fail because they load multiple versions of a library. This is the case for example of the JavassistClassDeclarationTest class.

**Comment by jlerbsc** [comment] 2021-03-08 09:20
Now I fully understand the problem. The PR #3134 resolve the issue related to relation between librairies but i added A PR #3126 (commit 73e0428)  which should improve the performance of JP when trying to get the javassists definition of a class via the ClasspathElement.toCtClass () method. The modification consisted in creating a class (in the javassists sense) only when it did not exist. However, this modification is not compatible with loading several versions of the same class and using a single instance of ClassPool.

**Closed as completed** 2021-03-16 19:40 UTC
Labels: Bug report, Symbol Solver
