### ISSUE TITLE
Add exemple in javadoc for every node type

### ISSUE THREAD

**Issue by DeepSnowNeeL** [javaparser/javaparser#587] opened 2016-11-22 09:49 UTC
I often find myself wondering about what WildcardType or TypeParameter represents (among others)

It would be great to have some few exemples of small code which represents the node (with the node corresponding part highlighted) in the node javadoc

Like we already have in all import nodes (SingleStaticImportDeclaration...)

Thanks

**Comment by matozoid** [comment] 2016-11-22 10:40
This is a duplicate of #347, I think it would be good to pick it up during the 3.0 release candidate phase.

**Closed as completed by matozoid** 2016-11-22 10:40 UTC
