### ISSUE TITLE
Error while parsing class with utf-8 or 16 special literals

### ISSUE THREAD

**Issue by DeepSnowNeeL** [javaparser/javaparser#364] opened 2016-07-13 12:44 UTC
Here is the error :

> com.github.javaparser.TokenMgrError: Lexical error at line 15, column 57.  Encountered: "\u201d" (8221), after : "\'\u00e2"
>         at com.github.javaparser.ASTParserTokenManager.getNextToken(ASTParserTokenManager.java:2480)
>         at com.github.javaparser.ASTParser.jj_ntk(ASTParser.java:9154)
>         at com.github.javaparser.ASTParser.VariableInitializer(ASTParser.java:1071)
>         at com.github.javaparser.ASTParser.VariableDeclarator(ASTParser.java:1034)
>         at com.github.javaparser.ASTParser.FieldDeclaration(ASTParser.java:1003)
>         at com.github.javaparser.ASTParser.ClassOrInterfaceBodyDeclaration(ASTParser.java:945)
>         at com.github.javaparser.ASTParser.ClassOrInterfaceBody(ASTParser.java:865)
>         at com.github.javaparser.ASTParser.ClassOrInterfaceDeclaration(ASTParser.java:470)
>         at com.github.javaparser.ASTParser.TypeDeclaration(ASTParser.java:398)
>         at com.github.javaparser.ASTParser.CompilationUnit(ASTParser.java:203)
>         at com.github.javaparser.JavaParser.parse(JavaParser.java:111)
>         at com.github.javaparser.JavaParser.parse(JavaParser.java:158)
>         at com.github.javaparser.JavaParser.parse(JavaParser.java:177)
>         at com.ic2.rpc.jwsdl.JWSDLBuilder.analysis(JWSDLBuilder.java:153)
>         at com.ic2.rpc.jwsdl.JWSDLBuilder$1.visitFile(JWSDLBuilder.java:119)
>         at com.ic2.rpc.jwsdl.JWSDLBuilder$1.visitFile(JWSDLBuilder.java:107)
>         at java.nio.file.Files.walkFileTree(Files.java:2670)
>         at java.nio.file.Files.walkFileTree(Files.java:2742)
>         at com.ic2.rpc.jwsdl.JWSDLBuilder.build(JWSDLBuilder.java:107)
>         at com.ic2.rpc.jwsdl.JWSDLBuilder.main(JWSDLBuilder.java:377)
>         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
>         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.lang.reflect.Method.invoke(Method.java:497)
>         at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:294)
>         at java.lang.Thread.run(Thread.java:745)

And the line in error (with the following lines because I guess it would crash too) :

```
    private static final char UPPER_LEFT_CORNER = '┌';
    private static final char UPPER_RIGHT_CORNER = '┐';
    private static final char HORIZONTAL_LINE = '─';
    private static final char VERTICAL_LINE = '│';
    private static final char INTERSECTION = '┼';
    private static final char INTERSECTION_HORIZONTAL_DOWN = '┴';
    private static final char INTERSECTION_VERTICAL_LEFT = '├';
    private static final char INTERSECTION_VERTICAL_RIGHT = '┤';
    private static final char LOWER_LEFT_CORNER = '└';
    private static final char LOWER_RIGHT_CORNER = '┘';
```

Thanks 

(Btw, why TokenMgrError extends Throwable and not RuntimeException or Exception ? It made me a hard time to catch() it due to this)

**Comment by matozoid** [comment] 2016-07-13 13:08
About TokenMgrError: that's been fixed on trunk with a JavaCC upgrade.

**Comment by matozoid** [comment] 2016-07-14 21:09
Can you add a PR to https://github.com/matozoid/javaparser-issue-364 that will make it break with this exception?

**Comment by DeepSnowNeeL** [comment] 2016-07-14 23:04
it looks like it's due to the environement, I ran it from a maven build (external, not in IDE) invoked by maven-exec-plugin exec:java, I can't reproduce it from anywhere else but the external console...

**Comment by matozoid** [comment] 2016-07-15 08:20
Encoding problems are always troublesome. Are you running on Windows?

**Comment by DeepSnowNeeL** [comment] 2016-07-15 08:31
Yes

Le ven. 15 juil. 2016 10:20, Danny van Bruggen notifications@github.com a
écrit :

**Comment by matozoid** [comment] 2016-07-15 09:07
And what exactly do you do? What is the external console? cmd.exe? Is your system set to French?

**Comment by DeepSnowNeeL** [comment] 2016-07-15 09:11
My system is in french, I use the git-bash (mingw) console to run the mvn
executable which invoke maven-exec-plugin.

If I run the eclipse embedded maven (Run as> maven build in eclipse IDE) it
builds just fine without any error.

I'll try to run it with cmd.exe as soon as I can (tonight)

Le ven. 15 juil. 2016 11:07, Danny van Bruggen notifications@github.com a
écrit :

**Comment by matozoid** [comment] 2016-07-15 09:40
Okay, reproduced it, it happened because of Windows' default encoding. I was using a parse method without specifying encoding, and on Windows it uses something that is not UTF-8. Pushed a fix to my sample project: https://github.com/matozoid/javaparser-issue-364

We may consider removing the "default encoding" methods since we've had more reports like this.

**Comment by DeepSnowNeeL** [comment] 2016-07-15 09:42
Great !
Maybe force it utf-8 and provide another method which accept a charset ?

Le ven. 15 juil. 2016 11:40, Danny van Bruggen notifications@github.com a
écrit :

**Comment by matozoid** [comment] 2016-07-15 09:47
See #281

**Closed as completed** 2016-08-24 17:59 UTC
Labels: Question (JP usage)
