### ISSUE TITLE
Comment appearing twice in CompilationUnit

### ISSUE THREAD

**Issue by DiogoTheCoder** [javaparser/javaparser#3042] opened 2021-01-18 16:26 UTC
Parsing a Java file, and I'm getting a comment in the file appearing twice in the CompilationUnit, as both `ForEachStmt` and `LineComment`

This results in the comment appearing twice when I try to print the `CompilationUnit`:
```java
package com.brunel.diogocosta.fyp.examples;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Refactor {

  public static void main(String[] args) {
    String[] name = { "Diogo", "Costa" };
    ArrayList<String> test = new ArrayList<>();
    test.add("Diogo");
    test.add("Costa");
    List<String> test2 = List.of("Diogo", "Costa");
    // List<String> test3 = Arrays.asList("Maria", "Costa");
    test2
      .stream()
      .forEach(
        testString -> {
          System.out.println(test);
        }
      );
    // List<String> test3 = Arrays.asList("Maria", "Costa");
  }
}
```

![image](https://user-images.githubusercontent.com/31896387/104940609-e4ecc780-59a9-11eb-8e21-7d0f74ed548d.png)

Java Code (being parsed):
```java
package com.brunel.diogocosta.fyp.examples;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

public class Refactor {

  public static void main(String[] args) {
    String[] name = { "Diogo", "Costa" };
    ArrayList<String> test = new ArrayList<>();
    test.add("Diogo");
    test.add("Costa");
    List<String> test2 = List.of("Diogo", "Costa");
    // List<String> test3 = Arrays.asList("Maria", "Costa");
    // Test mcTest
    for (String testString : test2) {
      System.out.println(test);
    }
  }
}

```

JavaParser code
```java
                File file = new File(params.getArguments().get(0).toString());
                String filePath = file.getPath().replaceAll("\"", "");
                Logger.getLogger(Logger.GLOBAL_LOGGER_NAME).info("Parsing Java code from file: " + filePath);
                CompilationUnit compilationUnit;
                try {
                    ParserConfiguration parserConfig = new ParserConfiguration();
                    parserConfig.setIgnoreAnnotationsWhenAttributingComments(true);
                    StaticJavaParser.setConfiguration(parserConfig);
                    compilationUnit = StaticJavaParser.parse(new FileInputStream(filePath));
                    List<VariableDeclarator> variableDeclarationExprs = compilationUnit.findAll(VariableDeclarator.class);
                    compilationUnit.findAll(ForEachStmt.class)
                        .stream()
                        .forEach(forEachStmt -> {
                            ExpressionStmt eStmt = new ExpressionStmt();
        
                            NameExpr iterableExpression = forEachStmt.getIterable().asNameExpr();
        
                            VariableDeclarator arrayDeclarationExpr = variableDeclarationExprs
                                .stream()
                                .filter(variableDeclarationExpr -> variableDeclarationExpr.getName().equals(iterableExpression.getName()))
                                .findFirst()
                                .get();
        
                            // Arrays.stream(name) or name.stream()
                            MethodCallExpr methodCallExprArrays = new MethodCallExpr();
                            // stream
                            SimpleName simpleNameStream = new SimpleName("stream");
        
                            // Is this an array, e.g. String[]?
                            Type arrayDeclarationType = arrayDeclarationExpr.getType();
                            NameExpr nameExprArrays;
                            if (arrayDeclarationType.isArrayType()) {
                                compilationUnit.addImport(new ImportDeclaration("java.util.Arrays", false, false));
                                nameExprArrays = new NameExpr(new SimpleName("Arrays"));
        
                                // Name of the array to loop, argument for Arrays.stream()
                                methodCallExprArrays.setArguments(new NodeList<Expression>(iterableExpression));
                            } else {
                                nameExprArrays = iterableExpression;
                            }
        
                            nameExprArrays.setParentNode(methodCallExprArrays);
                            methodCallExprArrays.setScope(nameExprArrays);
                            methodCallExprArrays.setName(simpleNameStream);
        
                            // Arrays.stream(name), forEach, "string -> {
                            MethodCallExpr methodCallExpr = new MethodCallExpr();
        
                            // forEach
                            methodCallExpr.setName(new SimpleName("forEach"));
        
                            // string
                            Parameter parameterString = new Parameter(new UnknownType(),forEachStmt.getVariableDeclarator().getName());
                            // "string -> {
                            LambdaExpr lambdaExpr = new LambdaExpr(parameterString, (BlockStmt) forEachStmt.getBody());
        
                            // Arrays.streams(name), "string ->
                            methodCallExpr.setArguments(new NodeList<Expression>(lambdaExpr));
        
                            methodCallExpr.setScope(methodCallExprArrays);
        
                            eStmt.setExpression(methodCallExpr);
        
                            forEachStmt.replace(eStmt);
                        });

                    return compilationUnit.toString(new PrettyPrinterConfiguration().setOrderImports(true));
                } catch (FileNotFoundException e) {
                    e.printStackTrace();
                }
```

**Comment by DiogoTheCoder** [comment] 2021-02-05 18:15
Having a space between the code and the comment, seems to fix the issue

**Comment by jlerbsc** [comment] 2021-02-14 10:34
This issue is not reproducible with this test case

    @Test
    void g() {
        String code = 
                "import java.util.ArrayList;\n" + 
                "import java.util.Arrays;\n" + 
                "import java.util.List;\n" + 
                "\n" + 
                "public class Refactor {\n" + 
                "\n" + 
                "  public static void main(String[] args) {\n" + 
                "    String[] name = { \"Diogo\", \"Costa\" };\n" + 
                "    ArrayList<String> test = new ArrayList<>();\n" + 
                "    test.add(\"Diogo\");\n" + 
                "    test.add(\"Costa\");\n" + 
                "    List<String> test2 = List.of(\"Diogo\", \"Costa\");\n" + 
                "    // List<String> test3 = Arrays.asList(\"Maria\", \"Costa\");\n" + 
                "    test2\n" + 
                "      .stream()\n" + 
                "      .forEach(\n" + 
                "        testString -> {\n" + 
                "          System.out.println(test);\n" + 
                "        }\n" + 
                "      );\n" + 
                "    // List<String> test3 = Arrays.asList(\"Maria\", \"Costa\");\n" + 
                "  }\n" + 
                "}";
        ParserConfiguration config = new ParserConfiguration();
        CompilationUnit cu = StaticJavaParser.parse(code);
        System.out.println(cu.toString());

**Comment by jlerbsc** [comment] 2022-11-25 18:43
Since this issue is not reproducible and there is no new information to investigate it further, I am closing this issue.

**Closed as completed by jlerbsc** 2022-11-25 18:43 UTC
Labels: Need test case, Not reproducible
