### ISSUE TITLE
Unable to remove node in only for LexicalPreservingPrinter

### ISSUE THREAD

**Issue by jalajmsft** [javaparser/javaparser#2998] opened 2020-12-30 06:16 UTC
I am trying to remove a node - variable Declaration, getting the following error only when using LexicalPreservingPrinter, if commented out the node is getting removed as expected and no exception is raised.

**Exception raised**

> java.lang.UnsupportedOperationException: kept child(ClassOrInterfaceType) vs "String"   <89>   (line 23,col 3)-(line 23,col 8)

**Parser.java**
```  
                CombinedTypeSolver typeSolver = new CombinedTypeSolver(new ReflectionTypeSolver(), new JavaParserTypeSolver(codeDir));

		// Use our Symbol Solver while parsing
		ParserConfiguration parserConfiguration = new ParserConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver));

		//parserConfiguration.setLexicalPreservationEnabled(true);
		// Parse all source files
		SourceRoot sourceRoot = new SourceRoot(codeDir.toPath());
		sourceRoot.setParserConfiguration(parserConfiguration);
		
		List<ParseResult<CompilationUnit>> parseResults;
		
		try {
			parseResults = sourceRoot.tryToParse("");
			// Now get all compilation units
			compilations = parseResults.stream()
		                                          .filter(ParseResult::isSuccessful)
		                                          .map(r -> r.getResult().get())
		                                          .collect(Collectors.toList());
			
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
                  // Code to LexicalPreservingPrinter
		for (int i =0; i < compilations.size(); i++) {
			CompilationUnit cuu = compilations.get(i);
			LexicalPreservingPrinter.setup(cuu);
			sourceRoot.setPrinter(cu -> LexicalPreservingPrinter.print(cu));
		}

                while (iterator<compilations.size()) {
			
			CompilationUnit cu = compilations.get(iterator); 
			iterator++;                 
                        cu.walk(VariableDeclarator.class, node -> {
	                        try {
		                       node.remove();
	                        }
	                        catch (Exception e){
		                        System.out.println("Excpetio..in --dec + "+e);
	                        }
                        });
              }
```

**SimpleFile.java**

```
public class SimpleFile {
	
	public void test() {
		String testVariable = "Treatment-wise-weblab";
                 int r = 0;
	}
}

```

**Comment by jlerbsc** [comment] 2020-12-30 08:28
Hi @jalajmsft what version of JP are you using?

**Comment by jlerbsc** [comment] 2020-12-31 13:41
You are right you cannot remove VariableDeclarator with vd.remove() but you can remove VariableDeclarator in VariableDeclarationExpr.

**Comment by jlerbsc** [comment] 2023-06-24 16:04
I'm closing this issue because this case is no longer reproducible in the current version of JP. However, although it is possible, it makes no sense to delete a variable declaration because in the following declaration "int r = 0;" the node corresponding to the variable declaration contains "r = 0". Removing this node would correspond to keeping the following expression "int;"

**Closed as completed by jlerbsc** 2023-06-24 16:04 UTC
Labels: Bug report
