### ISSUE TITLE
ProjectRoot is always Empty/ Null

### ISSUE THREAD

**Issue by Amit-1984** [javaparser/javaparser#3501] opened 2022-02-25 05:06 UTC
I am trying to parse all java source files in a user specified directory structure using "SymbolSolverCollectionStrategy" and every time it returns null. The code used to get ProjectRoot is as follows:

        	public static String PROJECT = "/home/VANSH/eclipse-workspace/Structural Tool/resources/src";
        	Path root = Paths.get(projectPath);
		ProjectRoot projectRoot = new SymbolSolverCollectionStrategy().collect(root);
		List<SourceRoot> sourceRoots = projectRoot.getSourceRoots();
		System.out.println(projectRoot);

Output is : ProjectRoot at /home/VANSH/eclipse-workspace/Structural Tool/resources/src with []
However, under resources/src i have one folder and one .java file

I am clueless and urgently needs a solution. Anybody help

**Comment by jlerbsc** [comment] 2022-02-26 17:34
Hi @Amit-1984 i did this test wirh ParserCollectionStrategy and SymbolSolverCollectionStrategy and there was no problem. Can you give us more informations on your issue?

**Comment by Amit-1984** [comment] 2022-03-02 13:05
@jlerbsc thanks for your quick response. Then why i am getting my output as null? Can you please guide me further.

I am trying to parse few java source files at "/home/VANSH/eclipse-workspace/Structural Tool/resources/src" location and it contains few direct source java files and few folder in it.

Thanks in advance

**Comment by jlerbsc** [comment] 2022-03-02 18:23
Perhaps it's related to the issue #3218 that is resolved in snapshot version

**Comment by jlerbsc** [comment] 2022-04-10 20:27
When you say folder i think you are talking about package. If not, the structure of the project is not really conventional.

**Comment by jlerbsc** [comment] 2022-04-11 10:27
I cannot reproduce this problem so I am closing this issue but you are invited to reopen it if you can enrich the description of the problem

**Closed as completed by jlerbsc** 2022-04-11 10:27 UTC
