### ISSUE TITLE
 javaparser throw Exception: UnsolvedSymbolException or RuntimeException

### ISSUE THREAD

**Issue by momo-tong** [javaparser/javaparser#3887] opened 2023-02-02 07:53 UTC
I use javaparser handling java source code  always  get err:
err1:  `UnsolvedSymbolException:Unsolved symbol : CommonTestSupport`
err2: `RuntimeException:Issue calculating the type of the scope of MethodCallExprContext{wrapped=user.getAuthorities().size()}`
where err1 always occur when handling like `class A extend B`, err2 occur when handling nested call expressions. 
I am newer for javaparser, looking forward to your reply. Thanks!

my handling code:
`ResolvedMethodDeclaration rmd= JavaParserFacade.get(typeSolver).solve(methodCallExpr, true).getCorrespondingDeclaration();`
where typeSolver is `com.github.javaparser.symbolsolver.resolution.typesolvers.CombinedTypeSolver`

source  code just like:
`public class SAMLUserDetailsServiceImplTest extends CommonTestSupport {

    @Autowired
    private SAMLUserDetailsServiceImpl userDetailsService;

    @Test
    public void testLoadUserBySAML() {
        // given
        NameID mockNameID = mock(NameID.class);
        when(mockNameID.getValue()).thenReturn(USER_NAME);
        SAMLCredential credentialsMock = mock(SAMLCredential.class);
`

**Comment by jlerbsc** [comment] 2023-02-02 09:08
For the first error it seems that the CombinedTypeSolver cannot find the class CommonTestSupport. But I can't say for sure because it's not clear how you initialize the solver type.
For the second error It may be related to the first one. Can you provide us with a simple test case that reproduces the error.

**Comment by jlerbsc** [comment] 2023-05-08 08:26
I'm closing this issue because we don't have enough information to analyze the cause of the problem you raise. Moreover, we have no answers to the questions that are being asked. You can reopen it if you can provide us with a test case that reproduces your problem.

**Closed as completed by jlerbsc** 2023-05-08 08:26 UTC
