### ISSUE TITLE
Wrong range calculation on ArrayType with multiple dimensions

### ISSUE THREAD

**Issue by mernst** [javaparser/javaparser#3838] opened 2023-01-07 21:27 UTC
In this example the end of column is 8 but should be 6. This is a regression; the value was correctly 6 in version 3.24.9, but is incorrectly 8 in version 3.24.10.  The regression was caused by commit https://github.com/javaparser/javaparser/commit/1fa450e427c9a68d72a5f9e1dbd2c96766cedeee.

```
@Test
void test0() {
	String src = "Long[][]";
	Type at = StaticJavaParser.parseType(src);
	at.getRange().get().withEndColumn(8);
}
```

[This comment](https://github.com/javaparser/javaparser/commit/1fa450e427c9a68d72a5f9e1dbd2c96766cedeee#diff-924a7bb8bf774bce3c5b2a2d57fc8f986c904a2c543eb8cc4cd607636ae4fc47R147-R152) in `ArrayType.java` is incorrect:

```
// The end range must be equals to the last array bracket pair in the list
// in the example below:
// Long[][]
//        ^
//        |
// this is the outermost range for the ArrayType
```

The type `Long[][]` represents "array of array of Long", as follows:

```
    Long []  []
    ^    ^   ^
    |    |   |
    |    |   array of Long
    |    array of array of Long
    Long
```

The outermost range for an array type is always the *first* set of array brackets in the Java syntax.

You can confirm this in the [FAQ](https://checkerframework.org/jsr308/specification/java-annotation-design.html#array-syntax) of the [Java Type Annotations Specification (JSR 308)](https://checkerframework.org/jsr308/specification/java-annotation-design.html), which explains:

"the order in which a programmer reads an array type or expression is left-to-right for the brackets, then left-to-right for the base type."

```
  type:                       String             []            []

  order of reading:  2------------->  1 ------------------------>
```

Analogously, the Java expression new String[2][5] is “new length-2 array of length-5 array of Strings”, whose brackets are also read left-to-right.  Types are read consistently with array `new` expressions (that is, brackets left-to-right).

This is a tricky issue (it's easy to make a mistake!) because the structure of the grammar in the JLS differs from the semantics (brackets left-to-right), which is an unfortunate inconsistency.

The simplest fix for the problem is to revert commit 1fa450e427c9a68d72a5f9e1dbd2c96766cedeee.

**Comment by jlerbsc** [comment] 2023-01-08 16:49
In JP the notion of range indicates a position in a character string, it is notably used by the lexical preserving printer to calculate the differences between 2 variations of an expression. This commit fixes a problem with the functioning of the LPP.

in JP a range is defined as " A range of characters in a source file, from "begin" to "end", including the characters at "begin" and "end"." Ranges are composed of Position which are defined in JP as "A position in a source file. Lines and columns start counting at 1."

**Comment by jlerbsc** [comment] 2023-01-27 13:15
I'm closing this issue because I consider it's not a regression but a bug fix.

**Closed as completed by jlerbsc** 2023-01-27 13:15 UTC
