### ISSUE TITLE
Import methods from Java Symbol Solver's "Type"

### ISSUE THREAD

**Issue by matozoid** [javaparser/javaparser#1154] opened 2017-09-20 18:28 UTC
These are possible:

```java
    boolean isArray();
    int arrayLevel();
    boolean isPrimitive();
    boolean isNull();
    boolean isReference(); // This is a confusing one...
    boolean isConstraint();
    boolean isReferenceType();
    boolean isVoid();
    boolean isTypeVariable();
    boolean isWildcard();
    ArrayType asArrayType();
    ReferenceType asReferenceType();
    TypeParameterDeclaration asTypeParameter();
    PrimitiveType asPrimitive();
    Wildcard asWildcard();
```
... these I don't know. @ftomassetti ?
```java
    String describe();
    Type replaceTypeVariables(TypeParameterDeclaration tp, Type replaced, Map<TypeParameterDeclaration, Type> inferredTypes);
    Type replaceTypeVariables(TypeParameterDeclaration tp, Type replaced);
    boolean mention(List<TypeParameterDeclaration> typeParameters);
    boolean isAssignableBy(Type other);
    TypeVariable asTypeVariable();
    LambdaConstraintType asConstraintType();
```

Also the question is how much this helps to integrate JSS. Not much I think?

**Comment by ftomassetti** [comment] 2017-09-21 08:04
Agreed that `isReference` and `isReferenceType` are confusing :)

Maybe we can start looking for a common interface defining a Type and see how to move from there.

The problem is that "resolved types" will have some extra methods (like, get all ancestors). I do not know if the implementation in JP should throw exception for those, or maybe look into the data to see if they find a delegate (from JSS). Something like:

```
List<Type> getAllAncestors() {
   if (data.get(TypeSolver).isPresent()) {
    return data.get(TypeSolver).getAllAncestors();
   }
  throw new IllegalStateException("Symbol resolution not setup");
}
```

Or maybe we could have a Type interface and a SolvedType interface, which would extend Type.

**Comment by ElvisMachuca** [comment] 2017-09-21 17:54
I have an issue with statement "if (data.get(TypeSolver).isPresent()){ ...}"

Can anyone say if TypeSolver has had an update? --Not Referring to the validity of "TypeNotFound" but rather, the input that is missing....is it harmonic or gaussian, then a single parser for this case, has to make the distintion of its solver.

Rewritten:

List<Type> getAllAncestors() {
   InputTypeStream ts = data.resolve().getInputTypeStream();
   if (data.get(ts.getChannel()).isPresent()) {
    return data.get(ts.getChannel()).getAllAncestors();
   }
  throw new IllegalStateException("Symbol resolution not setup");
}

darpanet and ieee fan

**Comment by matozoid** [comment] 2017-09-21 18:18
@ElvisMachuca can you open a new issue for that here? https://github.com/javaparser/javasymbolsolver/issues - it has nothing to do with this issue.

**Comment by matozoid** [comment] 2017-09-22 08:51
Would you like...
```
javaparser.SomeInterface <|--- javaparser.Type
javaparser.SomeInterface <|--- javasymbolsolver.Type
```
?

If so, let's think of a name.
`shared.Type` is annoying: now users have multiple `Type`s to choose from.
`JavaParserTypeInterface` is strange, but clear?

**Comment by matozoid** [comment] 2017-09-23 12:51
@ftomassetti ?

**Comment by ftomassetti** [comment] 2017-09-23 12:56
I think it lost my comment (or I forgot to submit it). I think that to decide if to start from JP or JSS Type interface we should consider what this interface should contain, the option I see are 2:
* we have a limited interface (without the methods that decide symbol resolution). In this case we start from JP Type
* we have a richer interface. In this case when symbol resolution is not available exceptions will be thrown. In this case we start from the JSS Type

Does it make sense?

**Comment by matozoid** [comment] 2017-09-23 13:03
Yes, I think. Currently we have JP Type and JSS Type. I think you suggested before to make an additional interface that both could implement. So I suggested a name for that. My feeling is that it's best totake small steps and only put the JP part in there right now. Am I mistaken? (This happens a lot ;-) )

**Comment by ftomassetti** [comment] 2017-09-23 13:15
The problem with putting just the methods for the JP part is that this will be not enough for JSS so that it will need to use a wrapper or some other mechanism to move to the richer interface.

What if we keep the JP Type and the method "toSolvedType"? where SolvedType would be the JSS Type

**Comment by matozoid** [comment] 2017-09-23 13:17
Can you open a PR for this?

(If it is more than just a conversion, maybe `solve` is a better method name?)

**Comment by ftomassetti** [comment] 2017-09-23 13:21
Yes, I will do that late next week (I will be travelling the first half of the week)

**Comment by matozoid** [comment] 2017-09-23 13:29
Thanks!

**Comment by ftomassetti** [comment] 2017-09-23 13:30
Thank you!

**Comment by matozoid** [comment] 2017-09-23 13:38
Thank us!

**Comment by ftomassetti** [comment] 2017-10-07 12:22
Should we close this one?

**Closed as completed** 2017-10-07 12:53 UTC
Labels: Improvement
