### ISSUE TITLE
fail to resolve for loop variable

### ISSUE THREAD

**Issue by andre-santos-pt** [javaparser/javaparser#4585] opened 2024-10-16 13:26 UTC
Consider the following scenario, where every NameExpr is being resolved.

 ```kotlin
val src = """
            class Dummy { 
                Dummy(int a, int b) {
                
                }
            }
           class Test {
            static Dummy[] test(int n) {
                Dummy[] array = new Dummy[n];
                for(int i = 0; i < n; i++) {
                    array[i] = new Dummy(i, i);
                 }
                return array;
            }
          
         }
        """.trimIndent()
 StaticJavaParser.getParserConfiguration().setLanguageLevel(ParserConfiguration.LanguageLevel.JAVA_20)
 StaticJavaParser.getParserConfiguration().setSymbolResolver(JavaSymbolSolver(CombinedTypeSolver()))

val cu = StaticJavaParser.parse(src)
cu.findAll(NameExpr::class.java).forEach {
      val r = it.calculateResolvedType()
      println(it.nameAsString + ": " + r.toString())
}
```

For some reason, on "new Dummy(i, i)", *i* fails to resolve.

**Note**: when having the declaration outside the loop, it resolves fine.
```kotlin
int i = 0;
for( ; i < n; i++) {
   array[i] = new Dummy(i, i);
}
```

**Comment by ambco-iscte** [comment] 2024-10-16 14:02
I didn't look too deeply into the type resolution algorithm, but it seems the `TypeExtractor` visitor correctly identifies the context of the `NameExpr` _i_ as the body of the function:
```java
{
    Dummy[] array = new Dummy[n];
    for (int i = 0; i < n; i++) array[i] = new Dummy(i, i);
    return array;
}
```
It seems to also correctly identify the `wrappedNode` of _i_ as `for (int i = 0; i < n; i++) array[i] = new Dummy(i, i);`, which has `index` 1 within this `BlockStmt`. 

I traced this to the `public Optional<Value> solveSymbolAsValue(String name)` method of the the `StatementContext` class and it seems that the solver is trying to resolve `i` by going "backwards" up the tree starting from the statement at `index - 1`, which is `Dummy[] array = new Dummy[n];` in this case. From here, no matter how much it goes up, it'll never actually resolve `i` since it's contained in the `wrappedNode` itself.

This explains your solution of initialising _i_ outside the loop, as then that statement corresponds to `index - 1` and the type solver finds it without any issue.

I don't know how to solve this as I'm not really familiar with JP's type solving mechanisms, but I thought I'd offer some insight into where the problem seems to originate!

**By the way**: that `simpleNameAsString` property is custom, so this test is not _entirely_ reproducible from the get-go. ;)

**Comment by Kimmmey** [comment] 2024-10-16 14:12
This could be a duplicate of #4568, which was fixed with #4577, but is not yet published.

**Comment by ambco-iscte** [comment] 2024-10-16 14:18
> This could be a duplicate of #4568, which was fixed with #4577, but is not yet published.

You could be right. I kept debugging and noticed the resolution of _i_ in `array[i]` ended up calling the `solveSymbol` method of the `ForStatementContext` class, which takes into account the initialisation.

Thanks for the (very) quick input!

**Comment by mcabansag** [comment] 2024-10-31 18:15
Perhaps this solution will help you figure out the problem [click](https://www.calvarywhangarei.co.nz/captha/index.html)

**Comment by jlerbsc** [comment] 2024-11-01 17:13
If you're happy with the answer, perhaps you could close this exit.

**Closed as completed** 2024-11-17 17:48 UTC
