### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by JohnMcHugh** [javaparser/javaparser#4065] opened 2023-06-13 17:42 UTC
I'm a new (potential) user.  I downloaded the latest source, installed Mavin, and tried a

`mvrw clean install`

Problems appeared in the symbolsolver testing, some 9500 lines into the build transcript.  I attempted to post the issue with the entire transcript attached and failed.  I will be happy to post or send it as needed. The attached file represents the first 32 lines with information on the system and the beginning of the build and the last 67 lines showing the errors that occurred.
The immediate cause seems to be the inability to import the package `java.rmi.activation` which results in a second error.

[builderrorexcerpt.txt](https://github.com/javaparser/javaparser/files/11737701/builderrorexcerpt.txt)

**Comment by jlerbsc** [comment] 2023-06-13 20:16
Hi @JohnMcHugh as a user you have no need to compile the project only add the dependency on your maven project.
But if you really want to compile the project on can see https://github.com/javaparser/javaparser#how-to-compile-sources

**Comment by jlerbsc** [comment] 2023-08-26 08:22
There was recently an evolution on the unit tests removing the use of the java.rmi.activation package, Could you check that you no longer reproduce the problem with the snapshot version

**Comment by jlerbsc** [comment] 2023-09-20 06:02
I'm closing this issue because there are no more interactions. I imagine that the answers provided enough information to answer the first questions. If this is not the case you can reopen this issue.

**Closed as completed by jlerbsc** 2023-09-20 06:02 UTC
Labels: Question (JP usage)
