### ISSUE TITLE
ModifierVisitor and LexicalPreservingPrinter

### ISSUE THREAD

**Issue by attiand** [javaparser/javaparser#1277] opened 2017-12-09 10:41 UTC
Thanks for providing LexicalPreservingPrinter. I try to add a chained method call for each found method call in a ModifierVisitor but I receive a UnsupportedOperationException when using LexicalPreservingPrinter.

```java
	static class AddFooCallModifierVisitor extends ModifierVisitor<Void> {
		@Override
		public Visitable visit(MethodCallExpr n, Void arg) {
			// Add a call to foo() on every found method call
			return new MethodCallExpr(n, "foo");
		}
	}

	@Test
	public void testInvokeModifierVisitor() throws IOException {
		String code = "class A {" + EOL +
				      "  public String message = \"hello\";" + EOL +
				      "   void bar() {" + EOL + 
				      "     System.out.println(\"hello\");" + EOL + 
				      "   }" + EOL +
				      "}";

		CompilationUnit cu = JavaParser.parse(code);
		LexicalPreservingPrinter.setup(cu);
		cu.accept(new AddFooCallModifierVisitor(), null);
	}
```

Givs me:
`
java.lang.UnsupportedOperationException: kept child(ClassOrInterfaceType) vs "String"   <89>   (line 2,col 10)-(line 2,col 15)
`
If I remove the _message_ attribute it works fine.
Any idea what I am doing wrong?

Is there a way to catch formatting errors like this and proceed the processing (with some minor formatting issues)?

**Comment by ftomassetti** [comment] 2017-12-11 18:40
The issue seems due to the fact it is trying to replace the message Variable declarator with itself. A fix for this is trivial, but still I should understand the root cause. Also, the produced code seems to have a couple of extra blank lines :(

**Closed as completed** 2017-12-11 19:45 UTC
Labels: Bug report

**Comment by loongchow** [comment] 2018-11-27 08:57
it seems not solved,i met the problem too
