### ISSUE TITLE
Problem with comments

### ISSUE THREAD

**Issue by helenocampos** [javaparser/javaparser#148] opened 2015-06-09 19:43 UTC
Hi guys, I'm building a tool using JavaParser. Recently I encountered a problem while trying to solve a bug on my tool that I think that might be a bug of JavaParser.
I have this method to evaluate:

 public static List<Avaliacao> calcularResultadoFinal(List<Avaliacao> avaliacoes) throws SQLException, ClassNotFoundException{
        for(Avaliacao avaliacao: avaliacoes){
//            if(avaliacao.obterAprovacao()){
//                avaliacao.setResultadoFinal("Aprovado");
//            }else{
//                avaliacao.setResultadoFinal("Reprovado");
//            }
            avaliacao.setEmAberto(false);
            avaliacao.editar();
        }
        return avaliacoes;
    }

When the Javaparser parser it, some comment lines are missing, check the image below:

![javaparser-comment-bug](https://cloud.githubusercontent.com/assets/5610771/8067794/68aef3a2-0ec6-11e5-9ff5-763044a35b83.png)

Am I missing something?

Edit:
I found the comments in the orphanComments, however the methodDeclaration toString() method didn't read them. Is it expected?

![javaparser-comment-bug2](https://cloud.githubusercontent.com/assets/5610771/8068040/cb432bea-0ec7-11e5-85aa-c4114e5da836.png)

**Comment by ftomassetti** [comment] 2015-06-09 20:06
Yes, they are "orphanComments". Probably the DumpVisitor do not consider them.

Basically we associate comments to the thing we suppose they are referring to and we classify as "orphanComments" the comments which are not associated to a node. The problem is that they could be anywhere (they do not have a precise position) so we have to use their position in the original code to place them when producing the code.

This should be done in DumpVisitor using calls like `printOrphanCommentsBeforeThisChildNode(n);` and `printOrphanCommentsEnding(n);`. We are probably missing one case of two. It seems we have to look into the way the for statement is handled.

I will work on a patch on this in next days (but if anyone else want to jump it and submit a patch feel free! I am not locking this one)

**Comment by helenocampos** [comment] 2015-06-09 20:21
Thanks for the reply @ftomassetti !

**Comment by ftomassetti** [comment] 2015-06-09 20:27
Thanks for reporting this and for using JavaParser!

Btw, is your tool open-source? Can I take a look to it? From the screenshot it seems interesting!

**Comment by helenocampos** [comment] 2015-06-09 22:01
Yes it will be open-source, it's for a research paper (and my graduation thesis) I'm working on. It's about generating a cyclomatic complexity graph from any java code to help on building unit test cases. 
The code is pretty ugly right now because I'm testing and learning a lot of new things, like how to use javaparser and another library that I'm using to render graphs  (Jung) . I plan on refactoring the whole thing whenever I have a working prototype. 

I made a commit with the actual version I'm working (struggling) on my computer right now, so you can have an idea what I'm talking about.

https://github.com/helenocampos/complexity-tool-mvn
https://github.com/helenocampos/complexity-tool-gui

@ftomassetti Looks like I was using an old version of the javaparser (1.0.8) , that's why it was not showing the comments properly. Now I'm using the right version. I'm sorry for the incovenience!!

**Comment by ftomassetti** [comment] 2015-06-10 16:14
Good luck with that! I wrote a few papers myself and I missed the experience :)

About this issue I would work on some additional tests, just to be sure. I think we need also to make more people aware of the new release (in this respect I had a post republished on DZone about JavaParser 2.1 http://java.dzone.com/articles/releasing-javaparser-21, and we have now 3.6K people informed about the new release :D)

**Comment by helenocampos** [comment] 2015-06-10 16:44
Nice! I'm referencing the project as well on the papers, so more people get to know it!

**Comment by ftomassetti** [comment] 2015-06-14 10:20
Thanks @helenocampos ! Looking forward to read those papers, if you have a draft to share!

**Comment by ftomassetti** [comment] 2015-06-14 10:30
So, this problem is already being solved in recent releases and PR #151 add a new test case to prove this is ok and prevent possible regressions.

I would close this issue now, feel free to reopen if you think is wrong.

**Closed as completed by ftomassetti** 2015-06-14 10:30 UTC
