### ISSUE TITLE
No value present

### ISSUE THREAD

**Issue by sakitA** [javaparser/javaparser#2437] opened 2019-11-27 11:43 UTC
Hello I used `LexicalPreservingPrinte` class to pretty print. But I got the below exception
```
 java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135) ~[?:1.8.0_201]
	at com.github.javaparser.printer.lexicalpreservation.PhantomNodeLogic.isPhantomNode(PhantomNodeLogic.java:58) ~[javaparser-core-3.15.5.jar:?]
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.findNodeForToken(LexicalPreservingPrinter.java:344) ~[javaparser-core-3.15.5.jar:?]
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.findNodeForToken(LexicalPreservingPrinter.java:349) ~[javaparser-core-3.15.5.jar:?]
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.findNodeForToken(LexicalPreservingPrinter.java:349) ~[javaparser-core-3.15.5.jar:?]
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.storeInitialText(LexicalPreservingPrinter.java:322) ~[javaparser-core-3.15.5.jar:?]
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.lambda$setup$0(LexicalPreservingPrinter.java:101) ~[javaparser-core-3.15.5.jar:?]
	at java.util.Optional.ifPresent(Optional.java:159) ~[?:1.8.0_201]
	at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter.setup(LexicalPreservingPrinter.java:100) ~[javaparser-core-3.15.5.jar:?]
```

and this is the my code example
```java
    protected String prettyPrint(CompilationUnit cu) {
        LexicalPreservingPrinter.setup(cu);
        return LexicalPreservingPrinter.print(cu);
    }
```

**Comment by MysterAitch** [comment] 2019-11-27 21:21
Hi, what code are you attempting to pretty print? Cheers

**Comment by sakitA** [comment] 2019-11-28 05:37
I could not share my code because of confidential data. But I will try to write a simple example and share with you

**Comment by sakitA** [comment] 2019-12-13 06:41
I could not prepare an example. Because when I generate the code with auto I got this error. Then I just copy the generated code with standard print and store in a file. Then I read the file and print the LexicalPreservingPrinter method everything works normally. But from the code, I can say that the problem is there is no check that values present or not so the code gives to us a `java.util.NoSuchElementException` error.

**Comment by matozoid** [comment] 2019-12-13 11:48
Hi @sakitA, it might be good to know that nobody working on JavaParser is getting paid. It is all done by people who think it is fun to work on it. There are over 400 issues open and quite a few fundamental problems to solve, and I can say that there are way, way too few volunteers to ever get things perfect.

Now, we can solve your problem. The input we have is "this exception is thrown for an unknown situation, somewhere in the LPP." That's not much. You are asking us to analyse and debug the whole lexical preserving printer for every possible situation where this exception can occur, and fix all of them. That will take a long, long time. Now, someone might be crazy enough to do that, but I can assure you that people will work on other issues first, mostly the ones that benefit themselves.

Three options:
1. Leave it like this and your problem won't get fixed.
2. Reproduce the problem and supply a scenario and your problem might get fixed.
3. Create a pull request with a fix, and your problem is fixed in the next release.

**Comment by sakitA** [comment] 2019-12-13 11:58
Hi @matozoid. I think you misunderstood. I did not ask anyone to analyze and find what is the problem. I used this library and got this error. So that opened an issue. If I found the problem why occurred then I will fix and share the solution.

**Comment by edefazio** [comment] 2019-12-13 15:03
Just out of curiosity...

when you say 

> because when I generate the code with auto I got this error.

do you mean:
[https://github.com/google/auto](https://github.com/google/auto) ?

thanks
Eric

**Comment by sakitA** [comment] 2019-12-13 15:10
Hi @edefazio. No. I mean when I use this library and generate java code and at the end print the `CompilationUnit` with using the `LexicalPreservingPrinter.setup(cu)` method I got the issue. Then I just create the same code manually and use this file and parse with `StaticJavaParser.parse()` method. This time everything is ok and no problem. So that I could not reproduce the error.

**Comment by edefazio** [comment] 2019-12-13 15:55
Here is how you can reproduce:
(I don't know if this is intentionally un-supported by LPP, but I think it represents what @sakitA is talking about...

basically IF you setup the LPP after you manually create a `CompilationUnit` then you get the "No Value Present" `NoSuchElementException`

```java
	public void testE() {
		String originalCode = "class A { int a; }";
		
		// you have to parse the code using JavaParser, as usual
		CompilationUnit cu = StaticJavaParser.parse(originalCode);
		//make a simple change
		cu.setPackageDeclaration("changed.pkg");
		cu.getClassByName("A").get().addMember( StaticJavaParser.parseMethodDeclaration("public void aMethod(){}"));
		
		LexicalPreservingPrinter.setup(cu);
		
		System.out.println( LexicalPreservingPrinter.print(cu) );
	}
```
Note this happens on setUp(...)

internally it's happening in `PhantomNodeLogic` specifically at this:
```java
boolean res = (node.getParentNode().isPresent() &&
                    !node.getParentNode().get().getRange().get().contains(node.getRange().get())
                    || inPhantomNode(node, LEVELS_TO_EXPLORE));
```
likely here:
```java
!node.getParentNode().get().getRange()
```
...because although there MAY be a parent, that parent may NOT have a Range (if we didnt read it from a File)

**Comment by sakitA** [comment] 2019-12-13 16:03
@edefazio thank you very much. yes, you are right error happens when I call the `setup` method. I edit my previous comment.

**Comment by truongthanh96** [comment] 2020-04-16 09:14
```java
    final String filePath = "<Below file path>";
    final com.github.javaparser.JavaParser javaParser = new JavaParser();
    ParserConfiguration parserConfiguration = new ParserConfiguration();
    parserConfiguration.setAttributeComments(true);
    parserConfiguration.setIgnoreAnnotationsWhenAttributingComments(false);
    parserConfiguration.setDoNotAssignCommentsPrecedingEmptyLines(false);
    parserConfiguration.setLexicalPreservationEnabled(true);
    Node node = null;
    final ParseResult<CompilationUnit> result =
            javaParser.parse(ResourceUtils.loadResourceAsStream(filePath)
                    );

    LexicalPreservingPrinter.setup(result.getResult().get());
```

This is one of the files that could cause above error.

https://github.com/elastic/elasticsearch/blob/master/distribution/tools/plugin-cli/src/main/java/org/elasticsearch/plugins/InstallPluginCommand.java

**Comment by truongthanh96** [comment] 2020-04-16 09:35
A quick strip down found out that.
This is the code that cause the error with LexicalPrinter
```java

class InstallPluginCommand extends EnvironmentAwareCommand {

    /** Downloads a zip from the url, into a temp file under the given temp dir. */
    // pkg private for tests
    @SuppressForbidden(reason = "We use getInputStream to download plugins")
    Path downloadZip(Terminal terminal, String urlString, Path tmpDir, boolean isBatch) throws IOException {
        terminal.println(VERBOSE, "Retrieving zip from " + urlString);
        URL url = new URL(urlString);
        Path zip = Files.createTempFile(tmpDir, null, ".zip");
        URLConnection urlConnection = url.openConnection();
        urlConnection.addRequestProperty("User-Agent", "elasticsearch-plugin-installer");
        try (
                InputStream in = isBatch
                        ? urlConnection.getInputStream()
                        : new TerminalProgressInputStream(urlConnection.getInputStream(), urlConnection.getContentLength(), terminal)
        ) {
            // must overwrite since creating the temp file above actually created the file
            Files.copy(in, zip, StandardCopyOption.REPLACE_EXISTING);
        }
        return zip;
    }



}

```

Remove either one or all of 2 comment lines before @Supress make setup LexicalPrinter successfully
```java

class InstallPluginCommand extends EnvironmentAwareCommand {


    @SuppressForbidden(reason = "We use getInputStream to download plugins")
    Path downloadZip(Terminal terminal, String urlString, Path tmpDir, boolean isBatch) throws IOException {
        terminal.println(VERBOSE, "Retrieving zip from " + urlString);
        URL url = new URL(urlString);
        Path zip = Files.createTempFile(tmpDir, null, ".zip");
        URLConnection urlConnection = url.openConnection();
        urlConnection.addRequestProperty("User-Agent", "elasticsearch-plugin-installer");
        try (
                InputStream in = isBatch
                        ? urlConnection.getInputStream()
                        : new TerminalProgressInputStream(urlConnection.getInputStream(), urlConnection.getContentLength(), terminal)
        ) {
            // must overwrite since creating the temp file above actually created the file
            Files.copy(in, zip, StandardCopyOption.REPLACE_EXISTING);
        }
        return zip;
    }



}

```

**Comment by edefazio** [comment] 2020-04-16 11:55
Although we DO have issues related to the LexicalPreservingPrinter as it related to Orphan comments I _cannot_ reproduce this problem as stated, but I think the problem with your example is... you are doing this and not setting `node` (its null) in `(LexicalPreservingPrinter.print(node)`:

```
Node node = null;
final ParseResult<CompilationUnit> result =
            javaParser.parse(ResourceUtils.loadResourceAsStream(filePath)
);

LexicalPreservingPrinter.setup(result.getResult().get());
LOG.info(LexicalPreservingPrinter.print(node));
```

I WAS able to read in the file you are talking about and this works fine:
```java
JavaParser javaParser = new JavaParser();
ParserConfiguration parserConfiguration = new ParserConfiguration();
parserConfiguration.setAttributeComments(true);
parserConfiguration.setIgnoreAnnotationsWhenAttributingComments(false);
parserConfiguration.setDoNotAssignCommentsPrecedingEmptyLines(false);
parserConfiguration.setLexicalPreservationEnabled(true);

//I used the same setup to read the file in from harddrive worked fine
CompilationUnit cu = javaParser.parse(_io.inFile("C:\\jdraft\\project\\jdraft\\src\\test\\java\\test\\JavaParserInternalsTest.java").getInputStream()).getResult().get();

LexicalPreservingPrinter.setup(cu);
LexicalPreservingPrinter.print(cu);
```

I am using `javaparser-core 3.15.17`

**Comment by truongthanh96** [comment] 2020-04-16 12:00
Thank you for your comment, I have updated my comment. The Lexical throw No value present during setup before get to the NullPointer error.
This error happen on 3.15.14. I am migrating to 3.15.17 now.

EDIT: 3.15.17 work perfectly fine for the above files. Thank you.

**Comment by MysterAitch** [comment] 2020-04-19 09:07
@truongthanh96 Thank you for the update that a later version works well for you now - it really is appreciated! 

If there's anything else please do follow up, otherwise please do close this when you are ready :)

**Closed as completed** 2020-05-31 23:19 UTC
Labels: Bug report, Lexical Preservation, help wanted
