### ISSUE TITLE
Unsolved method call expression reference in case of enum statements

### ISSUE THREAD

**Issue by admindomaindomain** [javaparser/javaparser#2325] opened 2019-08-08 10:53 UTC
Hi,

I'm facing a problem when trying to solve a method call expression which reference a declaration in a enum statement. Following, I leave a detail of my code.

      public enum EscapeMode {
          ... some code ...

          EscapeMode(String file, int size) {
              load(this, file, size);
          }

          ... some code ...
       }
   
My VoidVisitorAdapter class I've implemented to look for MCEs.

    public class MethodCallResolver extends VoidVisitorAdapter<Object>{
	
    public void visit(MethodCallExpr mce, Object arg) {
		super.visit(mce, arg);	
		try {
		JavaParserFacade jpf = JavaParserFacade.get((CombinedTypeSolver) arg);
	        SymbolReference<ResolvedMethodDeclaration> reference = jpf.solve(mce);
	        
	        if (reference.isSolved()) {
	        	ResolvedMethodDeclaration md = reference.getCorrespondingDeclaration();
	        	System.out.println("\t Solved : " + md.getQualifiedSignature());
	        	
	        	solved++;
	        }else {
	        	System.out.println("\t Not solved. Method Call: " + mce + ", line: " + mce.getBegin().get().line);
	        	
	        	unsolved++;
	        }
	        
		}catch(UnsolvedSymbolException e) {
			System.err.println("\t Error. Method Call: " + mce + ", line: " + mce.getBegin().get().line + ", " + e.getMessage());
			
			errors++;
		}
		
	}

Next, is the line printed for unsolved references. In this case the unsolved reference is relative to the method declaration presented at the beginning.

    Not solved. Method Call: Entities.EscapeMode.valueOf(escapeMode.name()), line: 542

Also I've noticed that all of my unsolved references are relative to enum method declaration.

Do you have any ideas of how to solve such MCE references?

**Comment by ehud-eshet** [comment] 2019-08-08 13:56
Hi,

I face a similar problem.
Whenever an enum contains parameters, any method call which pass that enum as argument will fail to be resolved.

See following example:

```    
public static enum SecurityPolicyScopedTemplatesKeys {
        ID("id"),
        NAME("name"),
        SUSPICIOUS("suspicious"),
        PPS_THRESHOLDS("pps_thresholds"),
        BANDWIDTH_THRESHOLDS("bandwidth_thresholds"),
        SOURCES_THRESHOLDS("sources_thresholds");

        private String displayName;

        private SecurityPolicyScopedTemplatesKeys(String displayName) {
            this.displayName = displayName;
        }

        public String getDisplayName() {
            return this.displayName;
        }
 }
```
The following method call expression is failed to be resolved:
```
if( !suspiciousPacketType.equals(SecurityPolicyScopedTemplatesKeys.SUSPICIOUS.getDisplayName()) ) {
...
}
```

**Comment by matozoid** [comment] 2019-08-08 14:04
Hello! There is currently no maintainer for the symbol solver. That means the best way to get a problem solved is to fix it yourself and submit a PR.

**Comment by d-kay23** [comment] 2020-05-04 08:33
Hello.
I've also faced this bug.
Any updates?

**Comment by jlerbsc** [comment] 2020-05-04 14:08
There is no problem on the current version.
If this test case is not appropriated to reproduce this issue please give us the corresponding test.

    String s = 
                "public class A {\n" +
                "  public enum SecurityPolicyScopedTemplatesKeys {\n" + 
                "        SUSPICIOUS(\"suspicious\");\n" + 
                "        private String displayName;\n" + 
                "        private SecurityPolicyScopedTemplatesKeys(String displayName) {\n" + 
                "            this.displayName = displayName;\n" + 
                "        }\n" + 
                "        public String getDisplayName() {\n" + 
                "            return this.displayName;\n" + 
                "        }\n" + 
                "  }" +
                "  public void m() {\n" +
                "    String s = SecurityPolicyScopedTemplatesKeys.SUSPICIOUS.getDisplayName(); \n" +
                "  }\n" +
                " }\n";
        TypeSolver typeSolver = new ReflectionTypeSolver();
        StaticJavaParser.getConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver));
        CompilationUnit cu = StaticJavaParser.parse(s);
        MethodCallExpr methodCallExpr = cu.findFirst(MethodCallExpr.class).get();
        ResolvedMethodDeclaration rd = methodCallExpr.resolve();
        System.out.println("\t Solved : " + rd.getQualifiedSignature());

returns

    Solved : A.SecurityPolicyScopedTemplatesKeys.getDisplayName()

**Comment by d-kay23** [comment] 2020-05-05 06:37
> There is no problem on the current version.
> If this test case is not appropriated to reproduce this issue please give us the corresponding test.
> 
> ```
> String s = 
>             "public class A {\n" +
>             "  public enum SecurityPolicyScopedTemplatesKeys {\n" + 
>             "        SUSPICIOUS(\"suspicious\");\n" + 
>             "        private String displayName;\n" + 
>             "        private SecurityPolicyScopedTemplatesKeys(String displayName) {\n" + 
>             "            this.displayName = displayName;\n" + 
>             "        }\n" + 
>             "        public String getDisplayName() {\n" + 
>             "            return this.displayName;\n" + 
>             "        }\n" + 
>             "  }" +
>             "  public void m() {\n" +
>             "    String s = SecurityPolicyScopedTemplatesKeys.SUSPICIOUS.getDisplayName(); \n" +
>             "  }\n" +
>             " }\n";
>     TypeSolver typeSolver = new ReflectionTypeSolver();
>     StaticJavaParser.getConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver));
>     CompilationUnit cu = StaticJavaParser.parse(s);
>     MethodCallExpr methodCallExpr = cu.findFirst(MethodCallExpr.class).get();
>     ResolvedMethodDeclaration rd = methodCallExpr.resolve();
>     System.out.println("\t Solved : " + rd.getQualifiedSignature());
> ```
> 
> returns
> 
> ```
> Solved : A.SecurityPolicyScopedTemplatesKeys.getDisplayName()
> ```

Have you tried the case from initial post?
Try to resolve the method ```SecurityPolicyScopedTemplatesKeys.valueOf("SUSPICIOUS")```
I've reproduced this problem with javaparser-symbol-solver-core 3.15.21

**Comment by jlerbsc** [comment] 2020-05-05 07:22
@matozoid and javaparser leader team, is it the correct approche to solve a declaration or a type since symbol solver is integrated in javaparser core library?

    public void visit(MethodCallExpr mce, Object arg) {
	super.visit(mce, arg);	
	try {
	JavaParserFacade jpf = JavaParserFacade.get((CombinedTypeSolver) arg);
        SymbolReference<ResolvedMethodDeclaration> reference = jpf.solve(mce);

**Comment by matozoid** [comment] 2020-05-05 12:03
I have no idea.

**Comment by MysterAitch** [comment] 2020-05-05 12:35
> I have no idea.

Me neither! 

I had hoped that maybe @matozoid had a clearer idea :laughing: 

Maybe @ftomassetti is around and could help out?

Having a "correct" (or "preferred"?) way to do parsing is something that has niggled for a while, given that there are at least three ways to do this I think.

Figuring out which approaches are intended as preferred has been on the to-do list for a while (versus e.g. "internal only" and maybe moving them to a `com.github.javaparser.internal.xxx`?). Maybe something for a separate issue?

**Comment by matozoid** [comment] 2020-05-05 13:54
Oh wait, I didn't read the question carefully, I thought this was about solving enums! The facade is old, deprecated stuff and should not be used. None of the documentation should mention it.

**Comment by d-kay23** [comment] 2020-05-05 14:55
@matozoid @jlerbsc 
I am pointing to the enum valueOf method, not to the facade:
```
String s =
                "public class ClassTest {\n" +
                        "    public enum SecurityPolicyScopedTemplatesKeys {\n" +
                        "        SUSPICIOUS(\"suspicious\");\n" +
                        "        private String displayName;\n" +
                        "\n" +
                        "        private SecurityPolicyScopedTemplatesKeys(String displayName) {\n" +
                        "            this.displayName = displayName;\n" +
                        "        }\n" +
                        "\n" +
                        "        public String getDisplayName() {\n" +
                        "            return this.displayName;\n" +
                        "        }\n" +
                        "    }\n" +
                        "\n" +
                        "    public void m() {\n" +
                        "        SecurityPolicyScopedTemplatesKeys a = SecurityPolicyScopedTemplatesKeys.valueOf(\"SUSPICIOUS\");\n" +
                        "    }\n" +
                        "}";
        TypeSolver typeSolver = new ReflectionTypeSolver();
        StaticJavaParser.getConfiguration().setSymbolResolver(new JavaSymbolSolver(typeSolver));
        CompilationUnit cu = StaticJavaParser.parse(s);
        MethodCallExpr methodCallExpr = cu.findFirst(MethodCallExpr.class).get();
        ResolvedMethodDeclaration rd = methodCallExpr.resolve();
        System.out.println("\t Solved : " + rd.getQualifiedSignature());
```
Exception:
```
Exception in thread "main" UnsolvedSymbolException{context='null', name='We are unable to find the method declaration corresponding to SecurityPolicyScopedTemplatesKeys.valueOf("SUSPICIOUS")', cause='null'}
	at com.github.javaparser.symbolsolver.JavaSymbolSolver.resolveDeclaration(JavaSymbolSolver.java:167)
	at com.github.javaparser.ast.expr.MethodCallExpr.resolve(MethodCallExpr.java:313)
	at Parser.main(Parser.java:41)
```
It should be resolved, because ```SecurityPolicyScopedTemplatesKeys.valueOf("SUSPICIOUS");``` is correct java expression.

**Comment by MysterAitch** [comment] 2020-05-11 12:10
@maartenc has kindly provided a fix! :heart: 

It'll be merged once the ci checks are complete :)

**Closed as completed** 2020-05-11 12:38 UTC
Labels: Bug report, Symbol Solver, help wanted
