### ISSUE TITLE
"enum" should not be a reserved keyword in Java 1.4 and lower

### ISSUE THREAD

**Issue by sdrgroup** [javaparser/javaparser#1012] opened 2017-07-21 09:14 UTC
private static void cloneChildren(JMeterTreeNode to, JMeterTreeNode from)
    {
        **Enumeration enum = from.children();**
        while (enum.hasMoreElements())
        {
            JMeterTreeNode child = (JMeterTreeNode) enum.nextElement();
            JMeterTreeNode childClone = (JMeterTreeNode) child.clone();
            childClone.setUserObject(
                ((TestElement) child.getUserObject()).clone());
            to.add(childClone);
            cloneChildren((JMeterTreeNode) to.getLastChild(), child);
        }
    }
When I parse the line 3, the exception output is as following:
Exception in thread "main" com.github.javaparser.ParseProblemException: (line 3,col 5) Parse error. Found  "Enumeration" <IDENTIFIER>, expected "}"

the version is 3.2.12

**Comment by ftomassetti** [comment] 2017-07-21 09:17
enum is a keyword in Java since Java 6 I think. Which version of Java is being used for compiling this code?

**Comment by matozoid** [comment] 2017-07-21 09:49
It's some custom enumeration, that's not it.

This is a snippet of code, not a compilation unit. What method are you using to parse it?

**Comment by ftomassetti** [comment] 2017-07-21 10:08
Yes, you are right that maybe he is not using the right method to parse this piece of code, however the name of the variable is "enum", which is a keyword so that will cause also an error even if he uses the right method to parse the code, I think.

**Comment by matozoid** [comment] 2017-07-21 12:26
Ahhhh I overlooked that. Yes, reproduced it.

**Comment by matozoid** [comment] 2017-07-21 12:29
It can be fixed by accepting `enum` as an identifier. I guess we should do the same for other keywords that weren't available in Java 1.0.

**Comment by ftomassetti** [comment] 2017-07-21 14:48
But it depends on the language level, right? I mean, in Java 9 `enum` cannot be an identifier: it is just a keyword

**Comment by matozoid** [comment] 2017-07-21 15:12
True, so with the motto "the parser accepts as much as possible. The validators will flag the errors." the parser should accept these as identifiers, and validators should be written that will add a `Problem` when an identifier is called `enum` starting from Java 5 or 6 or so.

**Comment by sdrgroup** [comment] 2017-07-22 02:43
Yes. they are old codes.
I will close this issue.
Thank you.

**Comment by matozoid** [comment] 2017-07-23 17:45
I'll keep this open until the issue is solved.

**Closed as completed** 2017-07-26 17:23 UTC
Labels: Bug report, Grammar
