### ISSUE TITLE
Unable to calculate the type of a parameter of a method call. Method call: 

### ISSUE THREAD

**Issue by ChengSense** [javaparser/javaparser#3745] opened 2022-11-02 13:49 UTC
code

```
public Tensor convx(int[] stride, int padding, Tensor... input) {
        return new TensorFunction("Convx", input) {

            public Object compute() {
                Tenser A = getInput(0), B = getInput(1);
                int heighs = stride[0], widths = stride[1];
                int height = (B.shape(1) - A.shape(1) + 2 * padding) / heighs + 1;
                int width = (B.shape(2) - A.shape(2) + 2 * padding) / widths + 1;
                Tenser<Tensor> C = zeroTensors(new int[]{A.shape(0)}, new int[]{height, width});
                forEach(B.shape(0), A.shape(0), (i, l) -> {
                    C.set(addx(C.get(l), conv(stride, padding, new Tensor(A.get(l)), new Tensor(B.get(i)))), l);
                });
                return C;
            }

            public void gradient() { }

        };
    }
```

```
public static class TypeCalculatorVisitor extends VoidVisitorAdapter<JavaParserFacade> {
        @SneakyThrows
        public void visit(MethodCallExpr expr, JavaParserFacade javaParserFacade) {
            super.visit(expr, javaParserFacade);
            try {
                SymbolReference<ResolvedMethodDeclaration> solve = javaParserFacade.solve(expr);
                boolean solved = solve.isSolved();
                if(solved){
                    ResolvedMethodDeclaration correspondingDeclaration = solve.getCorrespondingDeclaration();
                    if(correspondingDeclaration instanceof ReflectionMethodDeclaration){
                        Field field = ((ReflectionMethodDeclaration) correspondingDeclaration).getClass().getDeclaredField("method");
                        field.setAccessible(true);
                        Method method = (Method) field.get(correspondingDeclaration);
                        System.out.println(method.toGenericString());
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }

```

java.lang.RuntimeException: Unable to calculate the type of a parameter of a method call. Method call: C.set(addx(C.get(l), conv(stride, padding, new Tensor(A.get(l)), new Tensor(B.get(i)))), l), Parameter: addx(C.get(l), conv(stride, padding, new Tensor(A.get(l)), new Tensor(B.get(i))))

**Comment by jlerbsc** [comment] 2022-11-02 16:56
Hi @ChengSense Can you give us a small reproductible unit test and eventually the stacktrace produced.

**Comment by ChengSense** [comment] 2022-11-05 02:41
Hi @jlerbsc https://github.com/senseas/deep-learning/blob/TypeSolverTest/deep-framework/src/test/java/com/deep/framework/CombinedTypeSolverTest.java

**Comment by ChengSense** [comment] 2022-11-05 04:26
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/13984224/200100605-1fc02040-d65a-4867-b454-277fd5994e2a.png">

**Comment by ChengSense** [comment] 2022-11-05 04:34
```
JavaParserFacade  method 

public ResolvedType getTypeOfThisIn(Node node) {

    // TODO consider static methods
    // if (Objects.is node instanceof ClassOrInterfaceDeclaration) {
    //     return new ReferenceTypeImpl(getTypeDeclaration((ClassOrInterfaceDeclaration) node), typeSolver);
    // }
    // if (node instanceof EnumDeclaration) {
    //     JavaParserEnumDeclaration enumDeclaration = new JavaParserEnumDeclaration((EnumDeclaration) node, typeSolver);
    //     return new ReferenceTypeImpl(enumDeclaration, typeSolver);
    // }
    // if (node instanceof ObjectCreationExpr && ((ObjectCreationExpr) node).getAnonymousClassBody().isPresent()) {
    //     JavaParserAnonymousClassDeclaration anonymousDeclaration = new JavaParserAnonymousClassDeclaration((ObjectCreationExpr) node, typeSolver);
    //     return new ReferenceTypeImpl(anonymousDeclaration, typeSolver);
    // }
    
  if(node.getParentNode().isEmpty()){
    // TODO consider static methods
    if (Objects.is node instanceof ClassOrInterfaceDeclaration) {
        return new ReferenceTypeImpl(getTypeDeclaration((ClassOrInterfaceDeclaration) node), typeSolver);
    }
    if (node instanceof EnumDeclaration) {
        JavaParserEnumDeclaration enumDeclaration = new JavaParserEnumDeclaration((EnumDeclaration) node, typeSolver);
        return new ReferenceTypeImpl(enumDeclaration, typeSolver);
    }
    if (node instanceof ObjectCreationExpr && ((ObjectCreationExpr) node).getAnonymousClassBody().isPresent()) {
        JavaParserAnonymousClassDeclaration anonymousDeclaration = new JavaParserAnonymousClassDeclaration((ObjectCreationExpr) node, typeSolver);
        return new ReferenceTypeImpl(anonymousDeclaration, typeSolver);
    }
  }
  return getTypeOfThisIn(demandParentNode(node));
}
```

**Comment by jlerbsc** [comment] 2022-11-15 16:14
It seems to me that the type solver is not properly initialized in your example.

**Comment by ChengSense** [comment] 2022-11-16 02:05
Hi @jlerbsc I have debugged and confirmed the problem. (Tenser<Tensor>=C).get(l) returns a generic type. The signature of the addx (Tensor... input) method is not accurately inferred. The resolution of addx(C.get(l),conv(street, padding, new Tensor(A.get (l)),new Tensor(B.get (i))) fails

**Comment by jlerbsc** [comment] 2023-01-27 13:18
I'm closing this issue because we don't have a simple test case to reproduce the anomaly. You are free to reopen it if you can submit us a producible and simple unit test.

**Closed as completed by jlerbsc** 2023-01-27 13:18 UTC
Labels: Need test case
