### ISSUE TITLE
tokens ,; should be accepted at the end of Enum

### ISSUE THREAD

**Issue by tretail** [javaparser/javaparser#2296] opened 2019-07-15 12:35 UTC
While declaring values of Enum, it should be valid to end with the tokens `,;`

For example, this kind of test should work:
```
@Test
void addingConstants() {
    EnumDeclaration ed = consider("enum A {" + EOL 
           + " E1" + "," + EOL 
           + ";" + EOL
            "}");
    ed.getEntries().addLast(new EnumConstantDeclaration("E2"));
    assertTransformedToString("enum A {" + EOL +
            " E1," + EOL +
            " E2" + EOL + ";"
            "}", ed);
}
```

But actually, this trigger the exception:
```
at com.github.javaparser.printer.lexicalpreservation.Difference.applyKeptDiffElement(Difference.java:471)
at com.github.javaparser.printer.lexicalpreservation.Difference.apply(Difference.java:142)
at com.github.javaparser.printer.lexicalpreservation.LexicalPreservingPrinter$Observer.concreteListChange(LexicalPreservingPrinter.java:274)
at com.github.javaparser.ast.observer.PropagatingAstObserver.listChange(PropagatingAstObserver.java:72)
at com.github.javaparser.ast.NodeList.lambda$notifyElementAdded$1(NodeList.java:466)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at com.github.javaparser.ast.NodeList.notifyElementAdded(NodeList.java:466)
at com.github.javaparser.ast.NodeList.add(NodeList.java:70)
at com.github.javaparser.ast.NodeList.addLast(NodeList.java:197)
at com.github.javaparser.printer.lexicalpreservation.transformations.ast.body.EnumDeclarationTransformationsTest.addingConstants(EnumDeclarationTransformationsTest.java:84)
```

I can prepare a PR if you can point out where to touch.
Thank you

**Comment by matozoid** [comment] 2019-07-15 12:49
Thanks! I can't help you with where to look, it will need some more work. (Well, maybe poking around in ConcreteSyntaxModel will help?)

**Comment by tretail** [comment] 2019-07-16 05:49
Thanks for your answer. I took a look in the ConcreteSyntaxModel, but finally I tried to change the Difference#applyKeptDiffElement method.

Problem is while calculating the difference, the comma is not match in the original elements.
I ended up with the following modification:

```java
private void applyKeptDiffElement(...
...
if (kept.getTokenType() == originalTextToken.getTokenKind()) {
    originalIndex++;
    diffIndex++;
} else if (kept.isNewLine() && originalTextToken.isSpaceOrTab()) {
    originalIndex++;
    diffIndex++;
} else if (!kept.isWhiteSpaceOrComment() && originalTextToken.isToken(COMMA)) {
    /* For example, Enum entries might end with comma.
     * Another way to read: 
     * if you find any token that is not a space (enum's field, right closing brace, ...)
     * then this is the end of entries (and comma will not be found in the diff collection)
     */
    originalIndex++;
} else if (kept.isWhiteSpaceOrComment()) {
    diffIndex++;
}
...
```
This test is now green:
```java
@Test
void removingModifiers() {
    EnumDeclaration ed = consider("public enum A { E1, E2 }");
    ed.setModifiers(new NodeList<>());
    assertTransformedToString("enum A { E1, E2 }", ed);
}
```
Nevertheless, this test is still broken because of comparison failure:
```java
@Test
void addingConstants() {
    EnumDeclaration ed = consider("enum A { E1, }");
    ed.getEntries().addLast(new EnumConstantDeclaration("E2"));
    assertTransformedToString("enum A { E1, E2, }", ed);
}
```
```java
enum A { E1,E2
, }
```

I am not very confident with the modification, and this result surprises me a bit, I must have missed something.
I'll take a closer look in the week.

**Comment by matozoid** [comment] 2019-07-16 09:05
Hmmm, yes that is kind of unsatisfactory because a comma is definitely not whitespace, so it should not be checked in whitespace logic. I guess this is something that the list change logic should keep track of, but I guess it only deals with commas between elements.

**Comment by tkoft** [comment] 2019-07-16 20:38
+1, I'm experiencing a similar issue string lists in annotations.  I have a feeling this is generalized to any array literal actually? 

From the [Java specs](https://docs.oracle.com/javase/specs/jls/se7/html/jls-10.html#jls-10.6): "A trailing comma may appear after the last expression in an array initializer and is ignored."

**Comment by jlerbsc** [comment] 2020-11-08 09:28
This issue is no longer reproducible

    public class Issue2296Test extends AbstractLexicalPreservingTest {

    @Test
    public void test() {
        String EOL = LineSeparator.SYSTEM.asRawString();

        considerCode(
                "enum A {" + EOL +
                        " E1" + "," + EOL +
                        ";" + EOL +
                        "}");
        EnumDeclaration ed = cu.findFirst(EnumDeclaration.class).get();
        ed.getEntries().addLast(new EnumConstantDeclaration("E2"));
        assertTransformedToString("enum A {" + EOL +
                " E1," + EOL +
                " E2" + EOL + ";" +
                "}", ed);

    }
    }

**Closed as completed by jlerbsc** 2020-11-08 09:28 UTC
Labels: Bug report, Lexical Preservation
